# Generated by Django 2.1.1 on 2018-12-10 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('enabled', models.BooleanField(db_index=True, default=False, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_delegation_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Delegation',
                'verbose_name_plural': 'Delegations',
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('email_address', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_emailaddress_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Email Address',
                'verbose_name_plural': 'Email Addresses',
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_escalation_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Escalation',
                'verbose_name_plural': 'Escalations',
            },
        ),
        migrations.CreateModel(
            name='GroupSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_groupsubscription_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': "Group's Subscriptions",
                'verbose_name_plural': "Groups' Subscriptions",
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('subject', models.CharField(db_index=True, max_length=253, unique=True, verbose_name='subject')),
                ('originating_email', models.EmailField(db_index=True, default='TSCST-Support@hssbc.ca', max_length=254, verbose_name='from email address')),
                ('template_file', models.FilePathField(db_index=True, match='.*\\.email$', max_length=253, path='/home/serban/phsa/sbin/p_soc_auto/uhuru/templates/email', verbose_name='template file')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_subject_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Subscription Subject',
                'verbose_name_plural': 'Subscription Subjects',
            },
        ),
        migrations.CreateModel(
            name='SubjectHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('subject_header', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='subject header')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_subjectheader_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhuru.Subject', verbose_name='subject')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_subjectheader_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Subject Header',
                'verbose_name_plural': 'Subject Headers',
            },
        ),
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('subject_tag', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='tag')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_subjecttag_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhuru.Subject', verbose_name='subject')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_subjecttag_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Subject Tag',
                'verbose_name_plural': 'Subject Tags',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_subscriber_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('delegate', models.ManyToManyField(related_name='delegate_to', through='uhuru.Delegation', to='uhuru.Subscriber', verbose_name='Delegate to')),
                ('escalate', models.ManyToManyField(related_name='escalate_to', through='uhuru.Escalation', to='uhuru.Subscriber', verbose_name='Escalate to')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_subscriber_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='SubscriberGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('subscriber_group', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='subscriber group name')),
                ('group_email_address', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='group email address')),
                ('group_pager', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, verbose_name='group pager telephone number')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_subscribergroup_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('subscriber', models.ManyToManyField(db_index=True, to='uhuru.Subscriber', verbose_name='Team Member')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_subscribergroup_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Subscriber Group',
                'verbose_name_plural': 'Subscriber Groups',
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, unique=True, verbose_name='telephone')),
                ('is_sms', models.BooleanField(db_index=True, default=True, help_text='this is a pager or SMS capable telephone number', verbose_name='SMS capable')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_telephone_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhuru.Subscriber', verbose_name='subscriber')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_telephone_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_usersubscription_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhuru.Subject', verbose_name='subscribes to')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhuru.Subscriber', verbose_name='subscriber')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_usersubscription_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': "User's Subscriptions",
                'verbose_name_plural': "Users' Subscriptions",
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='subscribers',
            field=models.ManyToManyField(through='uhuru.UserSubscription', to='uhuru.Subscriber', verbose_name='users subscribing to this subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subscribing_groups',
            field=models.ManyToManyField(through='uhuru.GroupSubscription', to='uhuru.SubscriberGroup', verbose_name='groups subscribing to this subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_subject_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='groupsubscription',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhuru.Subject', verbose_name='subscribes to'),
        ),
        migrations.AddField(
            model_name='groupsubscription',
            name='subscribing_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhuru.SubscriberGroup', verbose_name='subscribing group'),
        ),
        migrations.AddField(
            model_name='groupsubscription',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_groupsubscription_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='escalate_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalate_to_subscriber', to='uhuru.Subscriber', verbose_name='Escalate to Team Member'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalate_from_subscriber', to='uhuru.Subscriber', verbose_name='Team Member'),
        ),
        migrations.AddField(
            model_name='escalation',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_escalation_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhuru.Subscriber', verbose_name='subscriber'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_emailaddress_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='delegate_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_to_subscriber', to='uhuru.Subscriber', verbose_name='Delegate to Team Member'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_from_subscriber', to='uhuru.Subscriber', verbose_name='Team Member'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uhuru_delegation_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['subject', 'subscriber'], name='uhuru_users_subject_80d00e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('subject', 'subscriber')},
        ),
        migrations.AddIndex(
            model_name='subjecttag',
            index=models.Index(fields=['subject_tag', 'subject'], name='uhuru_subje_subject_7484ef_idx'),
        ),
        migrations.AddIndex(
            model_name='groupsubscription',
            index=models.Index(fields=['subject', 'subscribing_group'], name='uhuru_group_subject_cd6f51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsubscription',
            unique_together={('subject', 'subscribing_group')},
        ),
    ]
