# Generated by Django 2.1.1 on 2018-12-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhuru', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subjecttag',
            name='uhuru_subje_subject_7484ef_idx',
        ),
        migrations.RemoveField(
            model_name='subjectheader',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjecttag',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='headers',
            field=models.ManyToManyField(to='uhuru.SubjectHeader', verbose_name='field headers for this subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tags',
            field=models.ManyToManyField(to='uhuru.SubjectTag', verbose_name='tags for this subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='template_file',
            field=models.FilePathField(db_index=True, match='.*\\.email$', max_length=253, path='/home/steodore/phsa/sbin/p_soc_auto/uhuru/templates/email', verbose_name='template file'),
        ),
    ]
