# Generated by Django 2.0.7 on 2018-08-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegexRule',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules_engine.Rule')),
                ('match_string', models.CharField(db_index=True, max_length=253, verbose_name='raise when matching')),
            ],
            options={
                'abstract': False,
            },
            bases=('rules_engine.rule', models.Model),
        ),
        migrations.AlterModelOptions(
            name='expirationrule',
            options={'verbose_name': 'Certificate Validity Rule', 'verbose_name_plural': 'Certificate Validity Rules'},
        ),
        migrations.AlterModelOptions(
            name='intervalrule',
            options={'verbose_name': 'Interval Rule', 'verbose_name_plural': 'Interval Rules'},
        ),
        migrations.RenameField(
            model_name='intervalrule',
            old_name='max_val',
            new_name='interval',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='action',
        ),
    ]
