# Generated by Django 2.0.7 on 2018-08-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0003_auto_20180830_2220'),
        ('rules_engine', '0003_auto_20180830_1805'),
    ]

    operations = [
    ]
