# Generated by Django 2.0.7 on 2018-09-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0004_merge_20180831_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tindataforruledemos',
            name='data_name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='data_name'),
        ),
    ]
