# Generated by Django 2.0.7 on 2018-09-11 20:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0005_auto_20180911_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalrule',
            name='interval',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='interval'),
        ),
        migrations.AlterField(
            model_name='intervalrule',
            name='min_val',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='minimum acceptable value'),
        ),
    ]
