# Generated by Django 2.1.1 on 2018-09-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0007_auto_20180918_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='escalation_subscribers',
            field=models.TextField(blank=True, help_text='send escalation notifications raised by this rule to these users. this will be replaced by a reference once a subscriptions application becomes available', null=True, verbose_name='rule escalation subscribers'),
        ),
        migrations.AddField(
            model_name='rule',
            name='subscribers',
            field=models.TextField(blank=True, help_text='send notifications raised by this rule to these users. this will be replaced by a reference once a subscriptions application becomes available', null=True, verbose_name='rule subscribers'),
        ),
        migrations.AddField(
            model_name='ruleapplies',
            name='escalation_subscribers',
            field=models.TextField(blank=True, help_text='send escalated notifications raised when applying this rule to this particular model-field combination to these users. this will be replaced by a reference once a subscriptions application becomes available', null=True, verbose_name='model-field escalation subscribers'),
        ),
        migrations.AddField(
            model_name='ruleapplies',
            name='subscribers',
            field=models.TextField(blank=True, help_text='send notifications raised when applying this rule to this particular model-field combination to these users. this will be replaced by a reference once a subscriptions application becomes available', null=True, verbose_name='model-field subscribers'),
        ),
        migrations.AlterField(
            model_name='ruleapplies',
            name='field_name',
            field=models.CharField(db_index=True, help_text='the name of the field where the rule fact resides', max_length=64, verbose_name='field name'),
        ),
    ]
