# Generated by Django 2.1.1 on 2018-09-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('rules_engine', '0008_auto_20180924_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='notification_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.NotificationLevel', verbose_name='Notification Level'),
        ),
        migrations.AddField(
            model_name='rule',
            name='notification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.NotificationType', verbose_name='Notification Type'),
        ),
    ]
