# Generated by Django 2.1.1 on 2018-09-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180925_1733'),
        ('rules_engine', '0009_auto_20180924_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='notification_level',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='ruleapplies',
            name='notification_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.NotificationLevel', verbose_name='Notification Level'),
        ),
        migrations.AddField(
            model_name='ruleapplies',
            name='notification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.NotificationType', verbose_name='Notification Type'),
        ),
    ]
