# Generated by Django 2.1.1 on 2018-09-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0010_auto_20180925_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleapplies',
            name='second_field_name',
            field=models.CharField(blank=True, db_index=True, help_text='the name of the field where the second rule fact resides', max_length=64, null=True, verbose_name='second field name'),
        ),
    ]
