# Generated by Django 2.1.1 on 2018-09-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0011_ruleapplies_second_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expirationrule',
            name='valid_after',
        ),
    ]
