# Generated by Django 2.1.1 on 2018-09-26 15:11

from django.db import migrations


def fill_in_notification_lookups(apps, schema_editor):
    model = apps.get_model('rules_engine', 'RuleApplies')
    notification_type = apps.get_model('notifications', 'NotificationType').\
        objects.filter(is_default=True).get()
    notification_level = apps.get_model('notifications', 'NotificationLevel').\
        objects.filter(is_default=True).get()

    model.objects.all().update(notification_type=notification_type,
                               notification_level=notification_level)


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0012_remove_expirationrule_valid_after'),
    ]

    operations = [
        migrations.RunPython(fill_in_notification_lookups,
                             reverse_code=migrations.RunPython.noop)
    ]
