# Generated by Django 2.1.1 on 2018-10-18 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_populate_brodcast_methods_for_notification_types'),
        ('rules_engine', '0013_fill_in_notification_lookups'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='notification_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='notifications.NotificationLevel', verbose_name='Notification Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='notification_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='notifications.NotificationType', verbose_name='Notification Type'),
            preserve_default=False,
        ),
    ]
