# Generated by Django 2.1.1 on 2018-10-09 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rules_engine', '0013_fill_in_notification_lookups'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDemoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('data_name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='data_name')),
                ('data_datetime_1', models.DateTimeField(verbose_name='data_datetime_1')),
                ('data_number_1', models.IntegerField(verbose_name='data_number_1')),
                ('data_string_1', models.CharField(max_length=16, verbose_name='data_string_1')),
                ('data_datetime_2', models.DateTimeField(verbose_name='data_datetime_2')),
                ('data_number_2', models.IntegerField(verbose_name='data_number_2')),
                ('data_string_2', models.CharField(max_length=16, verbose_name='data_string_2')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_engine_ruledemodata_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_engine_ruledemodata_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Sample data for demonstrating rules',
                'verbose_name_plural': 'Sample data for demonstrating rules',
            },
        ),
        migrations.RemoveField(
            model_name='notificationeventforruledemo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationeventforruledemo',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tindataforruledemos',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tindataforruledemos',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='NotificationEventForRuleDemo',
        ),
        migrations.DeleteModel(
            name='TinDataForRuleDemos',
        ),
    ]
