# Generated by Django 2.1.4 on 2019-01-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrionNodeAuxAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orion_node_id', models.BigIntegerField(db_index=True, help_text='Unique Identifier for an Orion Node', verbose_name='Orion NodeId')),
                ('alert_body', models.TextField(verbose_name='Custom Alert Body')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is disabled, the row will always be excluded from any active operation', verbose_name='enabled')),
            ],
        ),
    ]
