# Generated by Django 2.1.4 on 2019-01-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_flash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sslinvalidauxalert',
            name='self_url',
        ),
        migrations.RemoveField(
            model_name='ssluntrustedauxalert',
            name='self_url',
        ),
        migrations.AddField(
            model_name='sslinvalidauxalert',
            name='orion_node_port',
            field=models.BigIntegerField(db_index=True, default=433, verbose_name='Orion Node TCP Port'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssluntrustedauxalert',
            name='orion_node_port',
            field=models.BigIntegerField(db_index=True, default=433, verbose_name='Orion Node TCP Port'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sslinvalidauxalert',
            name='raised_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='alert first raised on'),
        ),
        migrations.AlterField(
            model_name='ssluntrustedauxalert',
            name='raised_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='alert first raised on'),
        ),
    ]
