# Generated by Django 2.1.4 on 2019-02-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_flash', '0002_auto_20190130_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslinvalidauxalert',
            name='ssl_md5',
            field=models.CharField(db_index=True, default='bogus', max_length=64, verbose_name='primary key md5 fingerprint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sslinvalidauxalert',
            name='ssl_self_url',
            field=models.URLField(blank=True, null=True, verbose_name='Custom SSL alert URL'),
        ),
        migrations.AddField(
            model_name='sslinvalidauxalert',
            name='validity_data',
            field=models.CharField(db_index=True, default='7 days', max_length=32, verbose_name='validity data'),
        ),
        migrations.AddField(
            model_name='sslinvalidauxalert',
            name='validity_info',
            field=models.CharField(db_index=True, default='expires in less than', max_length=64, verbose_name='validity info'),
        ),
        migrations.AddField(
            model_name='ssluntrustedauxalert',
            name='ssl_md5',
            field=models.CharField(db_index=True, default='bogus', max_length=64, verbose_name='primary key md5 fingerprint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssluntrustedauxalert',
            name='ssl_self_url',
            field=models.URLField(blank=True, null=True, verbose_name='Custom SSL alert URL'),
        ),
        migrations.AddIndex(
            model_name='sslinvalidauxalert',
            index=models.Index(fields=['validity_info', 'validity_data'], name='orion_flash_validit_634495_idx'),
        ),
    ]
