# Generated by Django 2.1.4 on 2019-02-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_flash', '0004_auto_20190206_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredsslalert',
            name='not_after',
            field=models.DateTimeField(db_index=True, verbose_name='not valid after'),
        ),
        migrations.AlterField(
            model_name='expiredsslalert',
            name='silenced',
            field=models.BooleanField(db_index=True, default=False, help_text='The Orion server will ignore this row when evaluating alert conditions. Note that this flag will be automatically reset every $configurable_interval', verbose_name='silence this alert?'),
        ),
        migrations.AlterField(
            model_name='expiressoonsslalert',
            name='not_after',
            field=models.DateTimeField(db_index=True, verbose_name='not valid after'),
        ),
        migrations.AlterField(
            model_name='expiressoonsslalert',
            name='silenced',
            field=models.BooleanField(db_index=True, default=False, help_text='The Orion server will ignore this row when evaluating alert conditions. Note that this flag will be automatically reset every $configurable_interval', verbose_name='silence this alert?'),
        ),
        migrations.AlterField(
            model_name='invalidsslalert',
            name='not_after',
            field=models.DateTimeField(db_index=True, verbose_name='not valid after'),
        ),
        migrations.AlterField(
            model_name='invalidsslalert',
            name='silenced',
            field=models.BooleanField(db_index=True, default=False, help_text='The Orion server will ignore this row when evaluating alert conditions. Note that this flag will be automatically reset every $configurable_interval', verbose_name='silence this alert?'),
        ),
        migrations.AlterField(
            model_name='untrustedsslalert',
            name='not_after',
            field=models.DateTimeField(db_index=True, verbose_name='not valid after'),
        ),
        migrations.AlterField(
            model_name='untrustedsslalert',
            name='silenced',
            field=models.BooleanField(db_index=True, default=False, help_text='The Orion server will ignore this row when evaluating alert conditions. Note that this flag will be automatically reset every $configurable_interval', verbose_name='silence this alert?'),
        ),
    ]
