# Generated by Django 2.1.4 on 2019-03-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_flash', '0005_auto_20190219_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredsslalert',
            name='cert_issuer_url',
            field=models.URLField(blank=True, null=True, verbose_name='SSL certificate issuing authority URL'),
        ),
        migrations.AddField(
            model_name='expiressoonsslalert',
            name='cert_issuer_url',
            field=models.URLField(blank=True, null=True, verbose_name='SSL certificate issuing authority URL'),
        ),
        migrations.AddField(
            model_name='invalidsslalert',
            name='cert_issuer_url',
            field=models.URLField(blank=True, null=True, verbose_name='SSL certificate issuing authority URL'),
        ),
        migrations.AddField(
            model_name='untrustedsslalert',
            name='cert_issuer_url',
            field=models.URLField(blank=True, null=True, verbose_name='SSL certificate issuing authority URL'),
        ),
    ]
