# Generated by Django 2.1.4 on 2019-03-13 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_flash', '0007_citrusborgloginalert_citrusborguxalert_deadcitrusbotalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citrusborgloginalert',
            options={'verbose_name': 'Citrix failed logon alert', 'verbose_name_plural': 'Citrix failed logon alerts'},
        ),
        migrations.AlterModelOptions(
            name='citrusborguxalert',
            options={'verbose_name': 'Citrix response time alert', 'verbose_name_plural': 'Citrix response time alerts'},
        ),
        migrations.AlterModelOptions(
            name='deadcitrusbotalert',
            options={'verbose_name': 'Citrix bot dead alert', 'verbose_name_plural': 'Citrix bot dead alerts'},
        ),
        migrations.RemoveField(
            model_name='citrusborguxalert',
            name='avg_response_time',
        ),
        migrations.RemoveField(
            model_name='citrusborguxalert',
            name='avg_response_time_threshold',
        ),
        migrations.AddField(
            model_name='citrusborguxalert',
            name='avg_logon_time',
            field=models.DurationField(default=datetime.timedelta(0, 10), help_text='logon time as reported by ControlUp', verbose_name='average logon time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citrusborguxalert',
            name='avg_storefront_connection_time',
            field=models.DurationField(default=datetime.timedelta(0, 1), help_text='storefront connection time as reported by ControlUp', verbose_name='average storefront connection time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citrusborguxalert',
            name='ux_threshold',
            field=models.DurationField(default=datetime.timedelta(0, 1), help_text='logon or storefront connection times larger than this value will trigger alerts', verbose_name='response time alert threshold'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citrusborguxalert',
            name='ux_threshold_seconds',
            field=models.BigIntegerField(default=1, help_text='it it easier to handle the response time alert threshold ifrounded to entire seconds', verbose_name='response time alert threshold in seconds'),
            preserve_default=False,
        ),
    ]
