# Generated by Django 2.1.4 on 2019-03-14 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orion_flash', '0008_auto_20190313_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citrusborgloginalert',
            name='measured_now',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='all the queries that populate these rows are filtered over a period of time defined as going back from this time point for the sampled time interval.in other words this is the definition of now. the default is the return of the now() function but the functions running the queries allow the use any moment in time for which we have data', verbose_name='starting point in time'),
        ),
        migrations.AlterField(
            model_name='citrusborgloginalert',
            name='measured_over_days',
            field=models.BigIntegerField(db_index=True, default=0, help_text='use this field to compare if threshold is specified in days', verbose_name='sampled interval in days'),
        ),
        migrations.AlterField(
            model_name='citrusborgloginalert',
            name='measured_over_hours',
            field=models.BigIntegerField(db_index=True, default=0, help_text='use this field to compare if threshold is specified in hours', verbose_name='sampled interval in hours'),
        ),
        migrations.AlterField(
            model_name='citrusborgloginalert',
            name='measured_over_mins',
            field=models.BigIntegerField(db_index=True, default=0, help_text='use this field to compare if threshold is specified in minutes', verbose_name='sampled interval in minutes'),
        ),
        migrations.AlterField(
            model_name='citrusborguxalert',
            name='measured_now',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='all the queries that populate these rows are filtered over a period of time defined as going back from this time point for the sampled time interval.in other words this is the definition of now. the default is the return of the now() function but the functions running the queries allow the use any moment in time for which we have data', verbose_name='starting point in time'),
        ),
        migrations.AlterField(
            model_name='citrusborguxalert',
            name='measured_over_days',
            field=models.BigIntegerField(db_index=True, default=0, help_text='use this field to compare if threshold is specified in days', verbose_name='sampled interval in days'),
        ),
        migrations.AlterField(
            model_name='citrusborguxalert',
            name='measured_over_hours',
            field=models.BigIntegerField(db_index=True, default=0, help_text='use this field to compare if threshold is specified in hours', verbose_name='sampled interval in hours'),
        ),
        migrations.AlterField(
            model_name='citrusborguxalert',
            name='measured_over_mins',
            field=models.BigIntegerField(db_index=True, default=0, help_text='use this field to compare if threshold is specified in minutes', verbose_name='sampled interval in minutes'),
        ),
        migrations.AlterField(
            model_name='deadcitrusbotalert',
            name='measured_now',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='all the queries that populate these rows are filtered over a period of time defined as going back from this time point for the sampled time interval.in other words this is the definition of now. the default is the return of the now() function but the functions running the queries allow the use any moment in time for which we have data', verbose_name='starting point in time'),
        ),
        migrations.AlterField(
            model_name='deadcitrusbotalert',
            name='measured_over_days',
            field=models.BigIntegerField(db_index=True, default=0, help_text='use this field to compare if threshold is specified in days', verbose_name='sampled interval in days'),
        ),
        migrations.AlterField(
            model_name='deadcitrusbotalert',
            name='measured_over_hours',
            field=models.BigIntegerField(db_index=True, default=0, help_text='use this field to compare if threshold is specified in hours', verbose_name='sampled interval in hours'),
        ),
        migrations.AlterField(
            model_name='deadcitrusbotalert',
            name='measured_over_mins',
            field=models.BigIntegerField(db_index=True, default=0, help_text='use this field to compare if threshold is specified in minutes', verbose_name='sampled interval in minutes'),
        ),
    ]
