# Generated by Django 2.1.4 on 2019-03-15 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orion_flash', '0010_auto_20190315_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citrusborgloginalert',
            name='host_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, verbose_name='host name'),
        ),
        migrations.AlterField(
            model_name='citrusborgloginalert',
            name='measured_now',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='all the queries that populate these rows are filtered over a period of time defined as going back from this time point for the sampled time interval.in other words this is the definition of now. the default is the return of the now() function but the functions running the queries allow the use any moment in time for which we have data', verbose_name='time reference point'),
        ),
        migrations.AlterField(
            model_name='citrusborguxalert',
            name='host_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, verbose_name='host name'),
        ),
        migrations.AlterField(
            model_name='citrusborguxalert',
            name='measured_now',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='all the queries that populate these rows are filtered over a period of time defined as going back from this time point for the sampled time interval.in other words this is the definition of now. the default is the return of the now() function but the functions running the queries allow the use any moment in time for which we have data', verbose_name='time reference point'),
        ),
        migrations.AlterField(
            model_name='deadcitrusbotalert',
            name='host_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, verbose_name='host name'),
        ),
        migrations.AlterField(
            model_name='deadcitrusbotalert',
            name='measured_now',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='all the queries that populate these rows are filtered over a period of time defined as going back from this time point for the sampled time interval.in other words this is the definition of now. the default is the return of the now() function but the functions running the queries allow the use any moment in time for which we have data', verbose_name='time reference point'),
        ),
    ]
