# Generated by Django 2.1.4 on 2019-03-15 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_flash', '0011_auto_20190315_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='citrusborgloginalert',
            name='measured_over',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citrusborguxalert',
            name='measured_over',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deadcitrusbotalert',
            name='measured_over',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deadcitrusbotalert',
            name='not_seen_for',
            field=models.CharField(blank=True, help_text='the difference between now and last_seen converted to a suitable time unit', max_length=64, null=True, verbose_name='not seen for'),
        ),
    ]
