# Generated by Django 2.1.1 on 2018-10-24 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NmapCertsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('node_id', models.BigIntegerField(db_index=True, help_text='this is the primary keyof the orion node instance as defined in the orion_integration application', verbose_name='orion node local id')),
                ('addresses', models.CharField(max_length=100)),
                ('not_before', models.DateTimeField(db_index=True, help_text='certificate not valid before this date', verbose_name='not before')),
                ('not_after', models.DateTimeField(db_index=True, help_text='certificate not valid after this date', verbose_name='not after')),
                ('xml_data', models.TextField()),
                ('common_name', models.CharField(db_index=True, help_text='the CN part of an SSL certificate', max_length=100, verbose_name='common name')),
                ('organization_name', models.CharField(blank=True, db_index=True, help_text='the O part of the SSL certificate', max_length=100, null=True, verbose_name='organization')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sig_algo', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bits', models.CharField(blank=True, max_length=100, null=True)),
                ('md5', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='md5')),
                ('sha1', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='sha1')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_nmapcertsdata_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_nmapcertsdata_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'SSL Certificate Data',
                'verbose_name_plural': 'SSL Certificate Data',
            },
        ),
        migrations.CreateModel(
            name='NmapCertsScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('command', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_nmapcertsscript_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_nmapcertsscript_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NmapHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.IntegerField()),
                ('orion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('md5', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('retreived', models.DateTimeField(blank=True, null=True)),
                ('xml_data', models.TextField()),
            ],
        ),
    ]
