# Generated by Django 2.1.1 on 2018-10-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nmapcertsscript',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='nmapcertsscript',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='NmapHistory',
        ),
        migrations.AlterModelOptions(
            name='nmapcertsdata',
            options={'verbose_name': 'SSL Certificate', 'verbose_name_plural': 'SSL Certificates'},
        ),
        migrations.DeleteModel(
            name='NmapCertsScript',
        ),
    ]
