# Generated by Django 2.0.7 on 2018-08-30 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssl_cert_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NmapCertsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('orion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('addresses', models.CharField(max_length=100)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('xml_data', models.TextField()),
                ('common_name', models.CharField(blank=True, help_text='A unique title for common_name', max_length=100, null=True)),
                ('organization_name', models.CharField(blank=True, help_text='A unique title for organization_name', max_length=100, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sig_algo', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('bits', models.CharField(blank=True, max_length=100, null=True)),
                ('md5', models.CharField(blank=True, max_length=100, null=True)),
                ('sha1', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_nmapcertsdata_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_nmapcertsdata_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NmapCertsScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('command', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_nmapcertsscript_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_nmapcertsscript_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NmapHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.IntegerField()),
                ('orion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('md5', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('retreived', models.DateTimeField(blank=True, null=True)),
                ('xml_data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestCertsData',
        ),
    ]
