# Generated by Django 2.1.4 on 2019-04-04 17:56

from django.db import migrations


def remove_getnmapdata(apps, schema_editor):
    apps.get_model(
        'django_celery_beat', 'periodictask').objects.filter(
            task__icontains='getnmapdata').all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0002_old_data_migrations'),
    ]

    operations = [
        migrations.RunPython(remove_getnmapdata,
                             reverse_code=migrations.RunPython.noop)
    ]
