# Generated by Django 2.1.1 on 2018-09-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0003_auto_20180918_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nmapcertsdata',
            options={'verbose_name': 'SSL Certificate Data', 'verbose_name_plural': 'SSL Certificate Data'},
        ),
    ]
