# Generated by Django 2.1.1 on 2018-10-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0003_historicalnmapcertsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SslExpiresIn',
            fields=[
            ],
            options={
                'verbose_name': 'Valid SSL Certificate',
                'verbose_name_plural': 'Valid SSL Certificates by expiration date',
                'proxy': True,
                'indexes': [],
            },
            bases=('ssl_cert_tracker.nmapcertsdata',),
        ),
        migrations.CreateModel(
            name='SslHasExpired',
            fields=[
            ],
            options={
                'verbose_name': 'SSL Certificate: expired',
                'verbose_name_plural': 'SSL Certificates: expired',
                'proxy': True,
                'indexes': [],
            },
            bases=('ssl_cert_tracker.nmapcertsdata',),
        ),
        migrations.CreateModel(
            name='SslNotYetValid',
            fields=[
            ],
            options={
                'verbose_name': 'SSL Certificate: not yet valid',
                'verbose_name_plural': 'SSL Certificates: not yet valid',
                'proxy': True,
                'indexes': [],
            },
            bases=('ssl_cert_tracker.nmapcertsdata',),
        ),
    ]
