# Generated by Django 2.2.6 on 2019-10-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0004_subscription_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sslcertificate',
            options={'verbose_name': 'SSL Certificate', 'verbose_name_plural': 'SSL Certificates'},
        ),
    ]
