# Generated by Django 2.1.1 on 2018-10-29 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssl_cert_tracker', '0004_sslexpiresin_sslhasexpired_sslnotyetvalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('subscription', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='subscription')),
                ('emails_list', models.TextField(verbose_name='subscribers')),
                ('from_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='from')),
                ('template_dir', models.CharField(max_length=255, verbose_name='email templates directory')),
                ('template_name', models.CharField(max_length=64, verbose_name='email template name')),
                ('template_prefix', models.CharField(default='email/', max_length=64, verbose_name='email template prefix')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_subscription_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_subscription_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
        ),
    ]
