# Generated by Django 2.2.6 on 2019-12-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0005_auto_20191031_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='subscription'),
        ),
    ]
