# Generated by Django 2.2.6 on 2019-12-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0005_auto_20191031_0900'),
        ('ssl_cert_tracker', '0005_auto_20191031_1010'),
    ]

    operations = [
    ]
