# Generated by Django 2.2.6 on 2019-12-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0005_auto_20191031_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='mute_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Do not send alerts until'),
        ),
    ]
