# Generated by Django 2.1.1 on 2018-10-29 22:10

from django.db import migrations
from django.contrib.auth.models import User


def populate_subscribtions(apps, schema_editor):
    subscription = apps.get_model('ssl_cert_tracker', 'Subscription')

    user = User.objects.filter(is_superuser=True).first()

    _subscription = subscription.objects.filter(subscription='SSL Reports')
    if _subscription.exists():
        return

    _subscription = subscription(subscription='SSL Reports',
                                 template_dir='ssl_cert_tracker/template/',
                                 template_prefix='email/',
                                 template_name='ssl_cert_email')
    _subscription.created_by_id = user.id
    _subscription.updated_by_id = user.id
    _subscription.save()


def truncate(apps, schema_editor):
    subscription = apps.get_model('ssl_cert_tracker', 'Subscription')
    subscription.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0005_subscription'),
    ]

    operations = [
        migrations.RunPython(populate_subscribtions, reverse_code=truncate)
    ]
