# Generated by Django 2.2.6 on 2019-12-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0006_merge_20191216_1508'),
        ('ssl_cert_tracker', '0006_auto_20191227_1045'),
    ]

    operations = [
    ]
