# Generated by Django 2.1.1 on 2018-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0006_populate_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='headers',
            field=models.TextField(default='common_name,expires_in,not_before,not_after', verbose_name='data headers'),
        ),
    ]
