# Generated by Django 2.1.1 on 2018-10-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0007_auto_20181031_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='from_email',
            field=models.CharField(blank=True, default=['donotreply@phsa_soc_automation.ca'], max_length=255, null=True, verbose_name='from'),
        ),
    ]
