# Generated by Django 2.1.1 on 2018-11-01 21:41

from django.db import migrations

tasks = ['ssl_cert_tracker.tasks.email_ssl_report',
         'ssl_cert_tracker.tasks.email_expired_ssl_report',
         'ssl_cert_tracker.tasks.email_invalid_ssl_report']


def populate_report_tasks_cronjobs(apps, schema_editor):
    tasks = [
        ('Email SSL Certificates Report Daily',
         'ssl_cert_tracker.tasks.email_ssl_report',
         'cron0700', '00', '07'),
        ('Email Expired SSL Certificates Report Daily',
         'ssl_cert_tracker.tasks.email_expired_ssl_report',
         'cron0700', '05', '07'),
        ('Email Invalid SSL Certificates Report Daily',
         'ssl_cert_tracker.tasks.email_invalid_ssl_report',
         'cron0700', '10', '07')]

    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    for _task in tasks:
        cron, _ = CrontabSchedule.objects.get_or_create(
            minute=_task[3], hour=_task[4], day_of_week='*', day_of_month='*',
            month_of_year='*')

        PeriodicTask.objects.create(
            crontab=cron, name=_task[0], task=_task[1])


def nichts(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0008_auto_20181031_0936'),
    ]

    operations = [
        migrations.RunPython(populate_report_tasks_cronjobs,
                             reverse_code=nichts)
    ]
