# Generated by Django 2.2.6 on 2020-01-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0003_remove_getnmapdata'),
        ('ssl_cert_tracker', '0008_adjust_subscription_emails'),
    ]

    operations = [
    ]
