# Generated by Django 2.1.1 on 2018-11-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0010_auto_20181116_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='from_email',
            field=models.CharField(blank=True, default=['TSCST-Support@hssbc.ca'], max_length=255, null=True, verbose_name='from'),
        ),
    ]
