# Generated by Django 2.2.6 on 2020-01-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0009_merge_20200121_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='subscription'),
        ),
    ]
