# Generated by Django 2.2.6 on 2020-03-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0011_auto_20200123_1457'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable('Subscription',
                                           'p_soc_auto_base_subscription')
            ],
            state_operations=[
                migrations.DeleteModel(name='Subscription', ),
            ],
        ),
    ]
