# Generated by Django 2.1.1 on 2018-12-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0011_auto_20181122_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnmapcertsdata',
            name='not_after',
            field=models.DateTimeField(db_index=True, help_text='certificate not valid after this date', verbose_name='not valid after'),
        ),
        migrations.AlterField(
            model_name='historicalnmapcertsdata',
            name='not_before',
            field=models.DateTimeField(db_index=True, help_text='certificate not valid before this date', verbose_name='not valid before'),
        ),
        migrations.AlterField(
            model_name='nmapcertsdata',
            name='not_after',
            field=models.DateTimeField(db_index=True, help_text='certificate not valid after this date', verbose_name='not valid after'),
        ),
        migrations.AlterField(
            model_name='nmapcertsdata',
            name='not_before',
            field=models.DateTimeField(db_index=True, help_text='certificate not valid before this date', verbose_name='not valid before'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='from_email',
            field=models.CharField(blank=True, default='TSCST-Support@hssbc.ca', max_length=255, null=True, verbose_name='from'),
        ),
    ]
