# Generated by Django 2.1.1 on 2018-12-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0011_auto_20181122_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='from_email',
            field=models.CharField(blank=True, default='TSCST-Support@hssbc.ca', max_length=255, null=True, verbose_name='from'),
        ),
    ]
