# Generated by Django 2.1.1 on 2018-12-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0012_auto_20181205_1442'),
        ('ssl_cert_tracker', '0012_auto_20181205_1248'),
    ]

    operations = [
    ]
