# Generated by Django 2.2.6 on 2020-07-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0015_auto_20200722_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificate',
            name='external_node_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='External node id, from the ExternalSslNode table used to link to the node in the web console', null=True, verbose_name='orion node identifier'),
        ),
    ]
