# Generated by Django 2.2.6 on 2020-08-25 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0016_sslcertificate_external_node_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sslcertificate',
            options={'get_latest_by': 'last_seen', 'verbose_name': 'SSL Certificate', 'verbose_name_plural': 'SSL Certificates'},
        ),
    ]
