# Generated by Django 2.1.4 on 2019-01-22 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ssl_cert_tracker', '0016_auto_20190107_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='SslCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('common_name', models.CharField(db_index=True, help_text='SSL certificate commonName field', max_length=253, unique=True, verbose_name='common name')),
                ('organization_name', models.CharField(blank=True, db_index=True, help_text='SSL certificate organizationName field', max_length=253, null=True, verbose_name='organization name')),
                ('country_name', models.CharField(blank=True, db_index=True, help_text='SSL certificate countryName field', max_length=2, null=True, verbose_name='country name')),
                ('orion_id', models.BigIntegerField(db_index=True, help_text='Orion Node unique identifier  on the Orion server used to show the node in the Orion web console', verbose_name='orion node identifier')),
                ('hostnames', models.TextField(verbose_name='host names')),
                ('not_before', models.DateTimeField(db_index=True, verbose_name='not valid before')),
                ('not_after', models.DateTimeField(db_index=True, verbose_name='expires on')),
                ('pem', models.TextField(verbose_name='PEM')),
                ('pk_bits', models.CharField(db_index=True, max_length=4, verbose_name='primary key bits')),
                ('pk_type', models.CharField(db_index=True, max_length=4, verbose_name='primary key type')),
                ('pk_md5', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='primary key md5 shecksum')),
                ('pk_sha1', models.TextField(verbose_name='primary key sha1 checksum')),
                ('last_seen', models.DateTimeField(db_index=True, verbose_name='last seen')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_sslcertificate_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SslCertificateIssuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('common_name', models.CharField(db_index=True, help_text='SSL certificate commonName field', max_length=253, unique=True, verbose_name='common name')),
                ('organization_name', models.CharField(blank=True, db_index=True, help_text='SSL certificate organizationName field', max_length=253, null=True, verbose_name='organization name')),
                ('country_name', models.CharField(blank=True, db_index=True, help_text='SSL certificate countryName field', max_length=2, null=True, verbose_name='country name')),
                ('is_trusted', models.BooleanField(db_index=True, default=False, help_text='is this a known SSL issuing authority (like Verisign or DigiCert)?', verbose_name='is trusted')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_sslcertificateissuer_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_sslcertificateissuer_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Issuing Authority for SSL Certificates',
                'verbose_name_plural': 'Issuing Authorities for SSL Certificates',
            },
        ),
        migrations.CreateModel(
            name='SslProbePort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('port', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='port')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_sslprobeport_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_sslprobeport_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Network Port',
                'verbose_name_plural': 'Network Ports',
            },
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ssl_cert_tracker.SslCertificateIssuer', verbose_name='Issued By'),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ssl_cert_tracker.SslProbePort', verbose_name='TCP port'),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssl_cert_tracker_sslcertificate_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
