# Generated by Django 2.2.6 on 2020-10-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0017_auto_20200825_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalsslnode',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sslcertificate',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sslcertificateissuer',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sslprobeport',
            old_name='created_on',
            new_name='created',
        ),
    ]
