# Generated by Django 2.1.4 on 2019-01-22 22:43
from django.contrib.auth.models import User, UserManager
from django.db import migrations


def add_default_ssl_port(apps, schema_editor):
    port = 443

    model = apps.get_model('ssl_cert_tracker', 'SslProbePort')

    user = User.objects.filter(is_superuser=True)
    if user.exists():
        user = user.first()
    else:
        user = User.objects.create(
            username='soc_su', email='soc_su@phsa.ca',
            password='soc_su_password', is_active=True, is_staff=True,
            is_superuser=True)
        user.set_password('soc_su_password')
        user.save()

    ssl_port = model(port=port, created_by_id=user.id, updated_by_id=user.id)
    ssl_port.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0017_auto_20190122_1441'),
    ]

    operations = [
        migrations.RunPython(add_default_ssl_port,
                             reverse_code=migrations.RunPython.noop)
    ]
