# Generated by Django 2.1.4 on 2019-01-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0019_auto_20190124_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcertificate',
            name='pk_bits',
            field=models.CharField(db_index=True, max_length=4, verbose_name='private key bits'),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='pk_md5',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='primary key md5 checksum (hex)'),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='pk_sha1',
            field=models.TextField(verbose_name='primary key sha1 checksum (hex)'),
        ),
        migrations.AlterUniqueTogether(
            name='sslcertificate',
            unique_together={('orion_id', 'port')},
        ),
    ]
