# Generated by Django 2.1.4 on 2019-01-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0020_auto_20190125_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcertificate',
            name='pk_md5',
            field=models.CharField(db_index=True, max_length=64, verbose_name='primary key md5 checksum (hex)'),
        ),
    ]
