# Generated by Django 2.1.4 on 2019-02-22 22:52
import pytz

from django.db import migrations


def add_beats_for_orion_flash(apps, schema_editor):
    timezone = pytz.timezone('America/Vancouver')

    periodic_tasks = [
        #         ('Dead Citrix monitoring bots alert',
        #          'citrus_borg.tasks.email_dead_borgs_alert', 10, 'minutes',),
        #         ('Dead Citrix farm hosts alert',
        #          'citrus_borg.tasks.email_dead_servers_alert', 12, 'hours',),
    ]

    cron_tasks = [
        {
            'name': 'Refresh Orion alerts for untrusted SSL certificates',
            'task': 'orion_flash.tasks.refresh_ssl_alerts',
            'args': '["orion_flash.untrustedsslalert"]',
            'kwargs': '{}',
            'crontab': {
                'minute': '01',
                'hour': '07,15,23',
                'day_of_week': '*',
                'day_of_month': '*',
                'month_of_year': '*',
                'timezone': timezone,
            },
        },
        {
            'name':
            ('Refresh Orion alerts for SSL certificates that will expire in'
             ' less than 90 days'),
            'task': 'orion_flash.tasks.refresh_ssl_alerts',
            'args': '["orion_flash.untrustedsslalert"]',
            'kwargs': '{"lt_days":90 }',
            'crontab': {
                'minute': '01',
                'hour': '07,15,23',
                'day_of_week': '*',
                'day_of_month': '*',
                'month_of_year': '*',
                'timezone': timezone,
            },
        },
    ]

    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    IntervalSchedule = apps.get_model(
        'django_celery_beat', 'IntervalSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    for _task in cron_tasks:
        cron, _ = CrontabSchedule.objects.get_or_create(
            minute=_task[3], hour=_task[2], day_of_week='*', day_of_month='*',
            month_of_year='*', timezone=timezone)

        PeriodicTask.objects.create(
            crontab=cron, name=_task[0], task=_task[1])

    for _task in periodic_tasks:
        interval, _ = IntervalSchedule.objects.get_or_create(
            every=_task[2], period=_task[3])

        PeriodicTask.objects.create(
            interval=interval, name=_task[0], task=_task[1])


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0024_add_ssl_ports'),
    ]

    operations = [
    ]
