# Generated by Django 2.1.4 on 2019-03-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0025_add_beats_for_orion_flash'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='alternate_email_subject',
            field=models.TextField(blank=True, help_text='this is the non conditional subject of the email template.', null=True, verbose_name='fallback email subject'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='email_subject',
            field=models.TextField(blank=True, help_text='this is the conditional subject of the email template. it is normally just a fragment that will augmented by other variables', null=True, verbose_name='email subject fragment'),
        ),
    ]
