# Generated by Django 2.1.4 on 2019-03-26 21:32

from django.db import migrations


def update_subscription(apps, schema_editor):
    Subscription = apps.get_model('ssl_cert_tracker', 'subscription')

    subscription = Subscription.objects.get(
        subscription='Citrix logon event and ux summary')

    subscription.email_subject = (
        'Logon Events and Response Time Summary over the Last')
    subscription.alternate_email_subject = (
        'Logon Events and Response Time Summary by Hour')
    subscription.headers = '{},undetermined_events'.format(
        subscription.headers)

    subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0026_auto_20190326_1430'),
    ]

    operations = [
        migrations.RunPython(update_subscription,
                             reverse_code=migrations.RunPython.noop)
    ]
