# Generated by Django 2.1.4 on 2019-04-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert_tracker', '0028_update_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnmapcertsdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalnmapcertsdata',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnmapcertsdata',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='nmapcertsdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='nmapcertsdata',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalNmapCertsData',
        ),
        migrations.DeleteModel(
            name='NmapCertsData',
        ),
    ]
