# Generated by Django 2.2.6 on 2020-06-23 21:01

from django.db import migrations, models
import p_soc_auto_base.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SFTPUploadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=p_soc_auto_base.utils.get_uuid, unique=True, verbose_name='UUID')),
                ('errors', models.TextField(blank=True, null=True, verbose_name='Errors')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
            ],
        ),
    ]
