# Generated by Django 2.2.6 on 2020-06-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sftp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sftpuploadlog',
            name='host',
            field=models.TextField(default='sftp.phsa.ca', verbose_name='Host'),
            preserve_default=False,
        ),
    ]
