# Generated by Django 2.2.6 on 2020-10-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sftp', '0002_sftpuploadlog_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sftpuploadlog',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on'], 'verbose_name': 'SFTP Upload Log'},
        ),
    ]
