# Generated by Django 2.2.6 on 2021-02-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sftp', '0004_auto_20201027_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sftpuploadlog',
            options={'get_latest_by': 'created', 'ordering': ['-created'], 'verbose_name': 'SFTP Upload Log'},
        ),
    ]
