# Generated by Django 2.1.4 on 2019-06-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDiaryBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('expired', models.BooleanField(db_index=True, default=False, help_text='expired tasks will only be considered if specifically queried', verbose_name='expired')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='task ID')),
                ('task_name', models.CharField(db_index=True, max_length=253, verbose_name='task ID')),
            ],
        ),
    ]
