# Generated by Django 2.0.7 on 2018-08-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_soc_auto_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtf',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='WTF',
        ),
    ]
