# Generated by Django 2.2.6 on 2020-02-14 20:49

from django.db import migrations

from p_soc_auto_base.migrations import create_subscription


SLOW_SUB = {'subscription': 'Citrix Slow Alert',
            'template_name': 'ux_alarm_site_borg',
            'headers': 'created_on,source_host__site__site,'
                       'source_host__host_name,storefront_connection_duration,'
                       'logon_achieved_duration,receiver_startup_duration,'
                       'connection_achieved_duration,'
                       'receiver_startup_duration', }


def create_slow_sub(apps, schema_editor):
    create_subscription(apps, SLOW_SUB)


def remove_slow_sub(apps, schema_editor):
    subscription_model = apps.get_model('p_soc_auto_base', 'Subscription')
    subscription_model.filter(subscription='Citrix Slow Alert').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('p_soc_auto_base', '0002_subscriptions'),
    ]

    operations = [migrations.RunPython(create_slow_sub,
                                       reverse_code=remove_slow_sub)]
