# Generated by Django 2.2.6 on 2020-03-02 21:27

from django.db import migrations

from p_soc_auto_base.migrations import add_beats, remove_beats


TASK = ({'name': 'Delete old templated emails',
         'task': 'p_soc_auto_base.tasks.delete_emails',
         'kwargs': '{"days": 3}', },
        {'every': 24, 'period': 'hours', }, )


class Migration(migrations.Migration):

    dependencies = [
        ('p_soc_auto_base', '0003_citrix_slow_alert_subscription'),
    ]

    operations = [
        migrations.RunPython(
            add_beats([], [TASK]), reverse_code=remove_beats([TASK]))
    ]
