# Generated by Django 2.2.6 on 2020-02-27 22:49

from django.db import migrations

from p_soc_auto_base.migrations import create_subscription


CLUSTER_SUB = {'subscription': 'Citrix Cluster Alert',
               'template_name': 'citrix_cluster_page',
               'headers': '', }


def create_cluster_sub(apps, schema_editor):
    create_subscription(apps, CLUSTER_SUB)


def remove_cluster_sub(apps, schema_editor):
    subscription_model = apps.get_model('ssl_cert_tracker', 'Subscription')
    subscription_model.filter(subscription='Citrix Cluster Alert').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('p_soc_auto_base', '0003_citrix_slow_alert_subscription'),
    ]

    operations = [migrations.RunPython(create_cluster_sub,
                                       reverse_code=remove_cluster_sub)]
