# Generated by Django 2.2.6 on 2020-03-13 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p_soc_auto_base', '0005_delete_emails_beat'),
        ('ssl_cert_tracker', '0012_delete_subscription')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.CreateModel(
                    name='Subscription',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                        ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                        ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                        ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                        ('subscription', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='subscription')),
                        ('emails_list', models.TextField(verbose_name='subscribers')),
                        ('from_email', models.CharField(blank=True, default='TSCST-Support@hssbc.ca', max_length=255, null=True, verbose_name='from')),
                        ('template_dir', models.CharField(max_length=255, verbose_name='email templates directory')),
                        ('template_name', models.CharField(max_length=64, verbose_name='email template name')),
                        ('template_prefix', models.CharField(default='email/', max_length=64, verbose_name='email template prefix')),
                        ('email_subject', models.TextField(blank=True, help_text='this is the conditional subject of the email template. it is normally just a fragment that will augmented by other variables', null=True, verbose_name='email subject fragment')),
                        ('alternate_email_subject', models.TextField(blank=True, help_text='this is the non conditional subject of the email template.', null=True, verbose_name='fallback email subject')),
                        ('headers', models.TextField(default='common_name,expires_in,not_before,not_after', verbose_name='data headers')),
                        ('tags', models.TextField(blank=True, help_text='email classification tags placed on the subject line and in the email body', null=True, verbose_name='tags')),
                        ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p_soc_auto_base_subscription_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                        ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p_soc_auto_base_subscription_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                    ],
                ),
            ],
        ),

    ]
