# Generated by Django 2.2.6 on 2020-06-23 16:18
from django.db import migrations

from p_soc_auto_base.migrations import add_beats, remove_beats


class Migration(migrations.Migration):

    SFTP_TASK = ({'name': 'Upload SFTP file',
                  'task': 'sftp.tasks.upload_sftp_file', },
                 {'every': 10, 'period': 'minutes', },)

    dependencies = [
        ('p_soc_auto_base', '0006_auto_20200420_0928'),
    ]

    operations = [migrations.RunPython(
        add_beats([], [SFTP_TASK]),
        reverse_code=remove_beats([SFTP_TASK])),
    ]
