# Generated by Django 2.2.6 on 2020-06-29 21:40

from django.db import migrations

from p_soc_auto_base.migrations import create_subscription


SFTP_SUB = {'subscription': 'SFTP Alert',
            'template_name': 'sftp_error',
            'headers': 'created_on,host,errors', }


def create_sftp_sub(apps, schema_editor):
    create_subscription(apps, SFTP_SUB)


def remove_sftp_sub(apps, schema_editor):
    subscription_model = apps.get_model('p_soc_auto_base', 'Subscription')
    subscription_model.objects.filter(subscription='SFTP Alert').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('p_soc_auto_base', '0007_sftptask'),
    ]

    operations = [migrations.RunPython(create_sftp_sub,
                                       reverse_code=remove_sftp_sub)]
