# Generated by Django 2.2.6 on 2020-08-25 20:30

from django.db import migrations

from p_soc_auto_base.migrations import create_subscription


APP_SUB = {'subscription': 'App Activity Update',
            'template_name': 'app_activity', }


def create_sftp_sub(apps, schema_editor):
    create_subscription(apps, APP_SUB)


def remove_sftp_sub(apps, schema_editor):
    subscription_model = apps.get_model('p_soc_auto_base', 'Subscription')
    subscription_model.objects.filter(
        subscription=APP_SUB['subscription']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('p_soc_auto_base', '0008_sftpsub'),
    ]

    operations = [migrations.RunPython(create_sftp_sub,
                                       reverse_code=remove_sftp_sub)]