# Generated by Django 2.2.6 on 2020-08-25 20:54
from django.db import migrations

from p_soc_auto_base.migrations import add_beats, remove_beats


class Migration(migrations.Migration):

    APP_TASK = ({'name': 'Check App Activity',
                 'task': 'p_soc_auto_base.tasks.check_app_activity',
                 'args': '[24, {"name":"SSL Certificate Checks", "model":"ssl_cert_tracker.SslCertificate", "column":"last_seen"}, {"name":"LDAP Probes", "model":"ldap_probe.LdapProbeLog", "column":"created_on"}]',},
                {'every': 24, 'period': 'hours', },)

    dependencies = [
        ('p_soc_auto_base', '0009_appactivitysub'),
    ]

    operations = [migrations.RunPython(
        add_beats([], [APP_TASK]),
        reverse_code=remove_beats([APP_TASK])),
    ]
