# Generated by Django 2.2.6 on 2020-09-09 20:31


from django.db import migrations

from p_soc_auto_base.migrations import create_subscription


NO_ACTIVITY_SUB = {'subscription': 'No Activity',
                   'template_name': 'no_activity', }


def create_sftp_sub(apps, schema_editor):
    create_subscription(apps, NO_ACTIVITY_SUB)


def remove_sftp_sub(apps, schema_editor):
    subscription_model = apps.get_model('p_soc_auto_base', 'Subscription')
    subscription_model.objects.filter(
        subscription=NO_ACTIVITY_SUB['subscription']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('p_soc_auto_base', '0010_appactivitytask'),
    ]

    operations = [migrations.RunPython(create_sftp_sub,
                                       reverse_code=remove_sftp_sub)]