# Generated by Django 2.2.6 on 2020-10-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_soc_auto_base', '0012_deletionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletionlog',
            options={'get_latest_by': 'created'},
        ),
        migrations.RenameField(
            model_name='deletionlog',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='created_on',
            new_name='created',
        ),
    ]
