# Generated by Django 2.1.4 on 2019-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbotmessage',
            name='mail_message_from',
        ),
        migrations.RemoveField(
            model_name='mailbotmessage',
            name='mail_message_to',
        ),
        migrations.AddField(
            model_name='mailbotmessage',
            name='received_by',
            field=models.TextField(blank=True, null=True, verbose_name='Received By'),
        ),
        migrations.AddField(
            model_name='mailbotmessage',
            name='received_from',
            field=models.TextField(blank=True, null=True, verbose_name='Received From'),
        ),
        migrations.AddField(
            model_name='mailbotmessage',
            name='sent_from',
            field=models.TextField(blank=True, null=True, verbose_name='Sent From'),
        ),
        migrations.AddField(
            model_name='mailbotmessage',
            name='sent_to',
            field=models.TextField(blank=True, null=True, verbose_name='Sent To'),
        ),
    ]
