# Generated by Django 2.1.4 on 2019-05-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0003_auto_20190529_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbotmessage',
            name='mail_message_identifier',
            field=models.CharField(db_index=True, max_length=36, verbose_name='Exchange Message Identifier'),
        ),
    ]
