# Generated by Django 2.1.4 on 2019-06-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0025_auto_20190603_1059'),
        ('mail_collector', '0005_auto_20190530_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailHost',
            fields=[
            ],
            options={
                'verbose_name': 'Exchange Monitoring Bot',
                'verbose_name_plural': 'Exchange Monitoring Bots',
                'ordering': ['-excgh_last_seen'],
                'get_latest_by': '-excgh_last_seen',
                'proxy': True,
                'indexes': [],
            },
            bases=('citrus_borg.winlogbeathost',),
        ),
        migrations.AlterModelOptions(
            name='mailbotlogevent',
            options={'get_latest_by': '-event_registered_on', 'ordering': ['-event_group_id'], 'verbose_name': 'Mail Monitoring Event', 'verbose_name_plural': 'Mail Monitoring Events'},
        ),
        migrations.AlterModelOptions(
            name='mailbotmessage',
            options={'get_latest_by': '-event__event_registered_on', 'ordering': ['-event__event_registered_on'], 'verbose_name': 'Mail Monitoring Message', 'verbose_name_plural': 'Mail Monitoring Messages'},
        ),
        migrations.AddField(
            model_name='mailbotlogevent',
            name='event_group_id',
            field=models.CharField(db_index=True, default='ham', help_text='Identifier for a group of related exchange client events', max_length=128, verbose_name='Session Id'),
            preserve_default=False,
        ),
    ]
