# Generated by Django 2.1.4 on 2019-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0007_auto_20190603_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbotlogevent',
            options={'get_latest_by': '-event_registered_on', 'ordering': ['-event_group_id', 'event_type_sort'], 'verbose_name': 'Mail Monitoring Event', 'verbose_name_plural': 'Mail Monitoring Events'},
        ),
        migrations.AlterModelOptions(
            name='mailbotmessage',
            options={'get_latest_by': '-event__event_registered_on', 'ordering': ['-event__event_group_id', 'mail_message_identifier', 'event__event_type_sort'], 'verbose_name': 'Mail Monitoring Message', 'verbose_name_plural': 'Mail Monitoring Messages'},
        ),
        migrations.AddField(
            model_name='mailbotlogevent',
            name='event_type_sort',
            field=models.IntegerField(db_index=True, default=999, help_text='connect (1) before sent (2) before received (3) and so on', verbose_name='Sort Value for Type'),
        ),
    ]
