# Generated by Django 2.1.4 on 2019-06-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0008_auto_20190606_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbotlogevent',
            options={'get_latest_by': '-event_registered_on', 'ordering': ['-event_group_id', 'mail_account', 'event_type_sort'], 'verbose_name': 'Mail Monitoring Event', 'verbose_name_plural': 'Mail Monitoring Events'},
        ),
    ]
