# Generated by Django 2.1.4 on 2019-06-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0010_auto_20190610_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeserver',
            name='last_connection',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time an account connected successfully to this server', null=True, verbose_name='Last Connected'),
        ),
        migrations.AlterField(
            model_name='exchangeserver',
            name='last_inbox_access',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Can also be considered as last received', null=True, verbose_name='Last Inbox Access'),
        ),
        migrations.AlterField(
            model_name='exchangeserver',
            name='last_send',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time a message was send via this server', null=True, verbose_name='Last Send'),
        ),
    ]
