# Generated by Django 2.1.4 on 2019-06-12 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0025_auto_20190603_1059'),
        ('mail_collector', '0012_auto_20190611_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBetweenDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_domain', models.CharField(db_index=True, max_length=63, verbose_name='Sent from email domain')),
                ('to_domain', models.CharField(db_index=True, max_length=63, verbose_name='Received by email domain')),
                ('is_expired', models.BooleanField(db_index=True, default=False, verbose_name='event has expired')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('last_verified', models.DateTimeField(db_index=True, verbose_name='Last Verified')),
            ],
            options={
                'verbose_name': 'Domain to Domain Mail Verification',
                'verbose_name_plural': 'Domain to Domain Mail Verifications',
                'ordering': ['site', 'from_domain', 'to_domain', '-last_verified'],
                'get_latest_by': '-last_verified',
            },
        ),
        migrations.CreateModel(
            name='MailSite',
            fields=[
            ],
            options={
                'verbose_name': 'Exchange Monitoring Site',
                'verbose_name_plural': 'Exchange Monitoring Sitess',
                'ordering': ['-winlogbeathost__excgh_last_seen'],
                'get_latest_by': '-winlogbeathost__excgh_last_seen',
                'proxy': True,
                'indexes': [],
            },
            bases=('citrus_borg.borgsite',),
        ),
        migrations.AddField(
            model_name='mailbetweendomains',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_collector.MailSite', verbose_name='Verified from mail site'),
        ),
        migrations.AddIndex(
            model_name='mailbetweendomains',
            index=models.Index(fields=['site', 'from_domain', 'to_domain'], name='mailbetweendomains_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailbetweendomains',
            unique_together={('site', 'from_domain', 'to_domain')},
        ),
    ]
