# Generated by Django 2.1.4 on 2019-06-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0013_auto_20190612_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbetweendomains',
            name='status',
            field=models.CharField(db_index=True, default='TBD', max_length=16, verbose_name='Status'),
        ),
    ]
