# Generated by Django 2.1.4 on 2019-06-17 18:54
from django.contrib.auth.models import User, UserManager

from django.db import migrations


def add_subscriptions(apps, schema_editor):
    to_emails = ('TSCST-Support@hssbc.ca,TSCST-Shiftmanager@hssbc.ca')

    subscriptions = [
        {
            'subscription': 'Exchange Servers Not Seen',
            'enabled': True,
            'emails_list': to_emails,
            'from_email': 'TSCST-Support@hssbc.ca',
            'template_dir': 'mail_collector/templates',
            'template_name': 'exc_serv_alert_all',
            'template_prefix': 'email/',
            'email_subject':
            'Exchange servers that have not serviced any requests over the last',
            'alternate_email_subject':
            'All Exchange Servers have serviced all requests over the last',
            'headers': ('exchange_server,last_updated'),
        },
        {
            'subscription': 'Exchange Servers No Connection',
            'enabled': True,
            'emails_list': to_emails,
            'from_email': 'TSCST-Support@hssbc.ca',
            'template_dir': 'mail_collector/templates',
            'template_name': 'exc_serv_alert_all',
            'template_prefix': 'email/',
            'email_subject':
            'Exchange servers that have not serviced any connection requests over the last',
            'alternate_email_subject':
            'All Exchange Servers have serviced all connection requests over the last',
            'headers': ('exchange_server,last_connected'),
        },
        {
            'subscription': 'Exchange Servers No Send', 'enabled': True,
            'emails_list': to_emails,
            'from_email': 'TSCST-Support@hssbc.ca',
            'template_dir': 'mail_collector/templates',
            'template_name': 'exc_serv_alert_all',
            'template_prefix': 'email/',
            'email_subject':
            'Exchange servers that have not serviced any send requests over the last',
            'alternate_email_subject':
            'All Exchange Servers have serviced all send requests over the last',
            'headers': ('exchange_server,last_send'),
        },
        {
            'subscription': 'Exchange Servers No Receive', 'enabled': True,
            'emails_list': to_emails,
            'from_email': 'TSCST-Support@hssbc.ca',
            'template_dir': 'mail_collector/templates',
            'template_name': 'exc_serv_alert_all',
            'template_prefix': 'email/',
            'email_subject':
            'Exchange servers that have not serviced any inbox access requests over the last',
            'alternate_email_subject':
            'All Exchange Servers have serviced all inbox access requests over the last',
            'headers': ('exchange_server,last_send'),
        },
        {
            'subscription': 'Exchange Databases Not Seen', 'enabled': True,
            'emails_list': to_emails,
            'from_email': 'TSCST-Support@hssbc.ca',
            'template_dir': 'mail_collector/templates',
            'template_name': 'exc_serv_alert_all',
            'template_prefix': 'email/',
            'email_subject':
            'Exchange Databases that have not serviced any inbox access requests over the last',
            'alternate_email_subject':
            'All Exchange Databases have serviced all inbox access requests over the last',
            'headers': ('exchange_server,last_send'),
        },
    ]

    subscription_model = apps.get_model('ssl_cert_tracker', 'subscription')

    user = User.objects.filter(is_superuser=True)
    if user.exists():
        user = user.first()
    else:
        user = User.objects.create(
            username='soc_su', email='soc_su@phsa.ca',
            password='soc_su_password', is_active=True, is_staff=True,
            is_superuser=True)
        user.set_password('soc_su_password')
        user.save()

    for subscription in subscriptions:
        subscription.update(dict(created_by_id=user.id, updated_by_id=user.id))
        subscription_instance = subscription_model(**subscription)
        subscription_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0015_auto_20190617_1023'),
    ]

    operations = [
        migrations.RunPython(add_subscriptions,
                             reverse_code=migrations.RunPython.noop)
    ]
