# Generated by Django 2.1.4 on 2019-06-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0019_subscriptions_mail_bots'),
    ]

    operations = [
    ]
