# Generated by Django 2.1.4 on 2019-06-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0015_auto_20190617_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangedatabase',
            name='last_updated_from_node_id',
            field=models.BigIntegerField(db_index=True, default=0, help_text='this is the value in this field to SQL join the Orion server database', verbose_name='Orion Node Id'),
        ),
        migrations.AddField(
            model_name='exchangeserver',
            name='last_updated_from_node_id',
            field=models.BigIntegerField(db_index=True, default=0, help_text='this is the value in this field to SQL join the Orion server database', verbose_name='Orion Node Id'),
        ),
        migrations.AddField(
            model_name='mailbetweendomains',
            name='last_updated_from_node_id',
            field=models.BigIntegerField(db_index=True, default=0, help_text='this is the value in this field to SQL join the Orion server database', verbose_name='Orion Node Id'),
        ),
    ]
