# Generated by Django 2.1.4 on 2019-06-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0021_auto_20190627_1213'),
    ]

    operations = [
    ]
