# Generated by Django 2.1.4 on 2019-07-05 22:04
from django.contrib.auth.models import User, UserManager

from django.db import migrations


def add_subscriptions(apps, schema_editor):
    to_emails = ('TSCST-Support@hssbc.ca,TSCST-Shiftmanager@hssbc.ca')

    subscriptions = [
        {
            'subscription': 'Exchange Send Receive By Site',
            'enabled': True,
            'emails_list': to_emails,
            'from_email': 'TSCST-Support@hssbc.ca',
            'template_dir': 'mail_collector/templates',
            'template_name': 'mail_events_by_site',
            'template_prefix': 'email/',
            'email_subject':
            'Exchange send receive events for site',
            'alternate_email_subject':
            'ERROR: No data for site ',
            'headers': (
                'mail_message_identifier,sent_from,sent_to,received_from,'
                'received_by,event__source_host__host_name,event__event_type,'
                'event__event_status,event__event_registered_on'),
        },
    ]

    subscription_model = apps.get_model('ssl_cert_tracker', 'subscription')

    user = User.objects.filter(is_superuser=True)
    if user.exists():
        user = user.first()
    else:
        user = User.objects.create(
            username='soc_su', email='soc_su@phsa.ca',
            password='soc_su_password', is_active=True, is_staff=True,
            is_superuser=True)
        user.set_password('soc_su_password')
        user.save()

    for subscription in subscriptions:
        subscription.update(dict(created_by_id=user.id, updated_by_id=user.id))
        subscription_instance = subscription_model(**subscription)
        subscription_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0022_add_subs_bot_site'),
    ]

    operations = [
        migrations.RunPython(add_subscriptions,
                             reverse_code=migrations.RunPython.noop)
    ]
