# Generated by Django 2.1.4 on 2019-07-09 19:06
from django.contrib.auth.models import User, UserManager

from django.db import migrations


def add_subscriptions(apps, schema_editor):
    to_emails = ('TSCST-Support@hssbc.ca,TSCST-Shiftmanager@hssbc.ca')

    subscriptions = [
        {
            'subscription': 'Exchange Failed Send Receive By Site',
            'enabled': True,
            'emails_list': to_emails,
            'from_email': 'TSCST-Support@hssbc.ca',
            'template_dir': 'mail_collector/templates',
            'template_name': 'mail_failed_events_by_site',
            'template_prefix': 'email/',
            'email_subject':
            'Exchange failed send receive events for site',
            'alternate_email_subject':
            'No Exchange failed send receive events for site ',
            'headers': (
                'mail_message_identifier,sent_from,sent_to,received_from,'
                'received_by,event__source_host__host_name,event__event_type,'
                'event__event_status,event__event_registered_on'),
        },
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0028_subscription_exc_fail_evts_bot'),
    ]

    operations = [
        migrations.RunPython(add_subscriptions,
                             reverse_code=migrations.RunPython.noop)
    ]
