# Generated by Django 2.2.3 on 2019-08-02 16:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_collector', '0021_auto_20190627_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('domain', models.CharField(db_index=True, max_length=15, verbose_name='windows domain')),
                ('username', models.CharField(db_index=True, max_length=64, verbose_name='domain username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='default windows account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_collector_domainaccount_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_collector_domainaccount_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Domain Account',
                'verbose_name_plural': 'Domain Accounts',
            },
        ),
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('smtp_address', models.EmailField(db_index=True, max_length=253, unique=True, verbose_name='Exchange Account')),
                ('exchange_autodiscover', models.BooleanField(default=True, verbose_name='use exchange auto discovery')),
                ('autodiscover_server', models.CharField(blank=True, max_length=253, null=True, verbose_name='Exchange discovery server')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_collector_exchangeaccount_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('domain_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail_collector.DomainAccount', verbose_name='Domain Account')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_collector_exchangeaccount_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Exchange Account',
                'verbose_name_plural': 'Exchange Accounts',
            },
        ),
        migrations.CreateModel(
            name='WitnessEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('smtp_address', models.EmailField(db_index=True, max_length=253, unique=True, verbose_name='Exchange Account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_collector_witnessemail_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_collector_witnessemail_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Witness Email Address',
            },
        ),
        migrations.CreateModel(
            name='ExchangeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('config_name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='name')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='default exchange monitoring client configuration')),
                ('debug', models.BooleanField(default=False, help_text='In debug mode the client will not clean up old messages', verbose_name='Debug')),
                ('autorun', models.BooleanField(default=True, help_text='When enabled, the client will execute mail checks automatically', verbose_name='Auto run')),
                ('mail_check_period', models.DurationField(default=datetime.timedelta(0, 3600), verbose_name='Execute email check every')),
                ('ascii_address', models.BooleanField(default=True, help_text='See https://tools.ietf.org/html/rfc5891 ', verbose_name='Format internationalized DNS domains to ASCII')),
                ('utf8_address', models.BooleanField(default=False, verbose_name='Allow UTF8 characters in the email address')),
                ('check_mx', models.BooleanField(default=True, verbose_name='Verify the domain part of the email address')),
                ('check_mx_timeout', models.DurationField(default=datetime.timedelta(0, 5), verbose_name='Timeout for verifying the domain part of the email address')),
                ('min_wait_receive', models.DurationField(default=datetime.timedelta(0, 3), verbose_name='Minimum waiting period before checking for a received message')),
                ('backoff_factor', models.IntegerField(default=3, verbose_name='Back-off factor for the waiting period before checking for a received message')),
                ('max_wait_receive', models.DurationField(verbose_name='Timeout while checking for a a received message')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Optional tags for the email subject line')),
                ('email_subject', models.CharField(default='exchange monitoring message', max_length=78, verbose_name='Email Subject Line')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_collector_exchangeconfiguration_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('exchange_accounts', models.ManyToManyField(limit_choices_to={'enabled': True}, to='mail_collector.ExchangeAccount', verbose_name='Exchange Accounts')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mail_collector_exchangeconfiguration_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('witness_addresses', models.ManyToManyField(limit_choices_to={'enabled': True}, to='mail_collector.WitnessEmail', verbose_name='CC the monitoring email messages to these addresses')),
            ],
            options={
                'verbose_name': 'Exchange Monitoring Client Configuration',
            },
        ),
        migrations.AddIndex(
            model_name='domainaccount',
            index=models.Index(fields=['domain', 'username'], name='mail_collec_domain_cdac27_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainaccount',
            constraint=models.UniqueConstraint(fields=('domain', 'username'), name='unique_account'),
        ),
    ]
