# Generated by Django 2.2.3 on 2019-08-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0032_auto_20190806_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeconfiguration',
            name='witness_addresses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'enabled': True}, to='mail_collector.WitnessEmail', verbose_name='CC the monitoring email messages to these addresses'),
        ),
    ]
