# Generated by Django 2.2.3 on 2019-08-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0035_add_exchange_config_default'),
        ('mail_collector', '0036_host_site_not_exist'),
    ]

    operations = [
    ]
