# Generated by Django 2.2.3 on 2019-08-21 21:30
from django.contrib.auth.models import User, UserManager

from django.db import migrations


def add_subscriptions(apps, schema_editor):
    to_emails = ('TSCST-Support@hssbc.ca,TSCST-Shiftmanager@hssbc.ca')

    subscriptions = [
        {
            'subscription': 'Mail Verification Report',
            'enabled': True,
            'emails_list': to_emails,
            'from_email': 'TSCST-Support@hssbc.ca',
            'template_dir': 'mail_collector/templates',
            'template_name': 'mail_verify_fail',
            'template_prefix': 'email/',
            'email_subject':
            'Email Verification Report',
            'alternate_email_subject':
            'Email Verification Report: no data. Please investigate immediately',
            'headers': (
                'from_domain,to_domain,site__site,status,last_verified'),
        },
        {
            'subscription': 'Mail Verification Failures Report',
            'enabled': True,
            'emails_list': to_emails,
            'from_email': 'TSCST-Support@hssbc.ca',
            'template_dir': 'mail_collector/templates',
            'template_name': 'mail_verify_fail',
            'template_prefix': 'email/',
            'email_subject':
            'Email Verification Failures Report',
            'alternate_email_subject':
            'Email Verification Failures Report: no failures',
            'headers': (
                'from_domain,to_domain,site__site,status,last_verified'),
        },
    ]

    subscription_model = apps.get_model('ssl_cert_tracker', 'subscription')

    user = User.objects.filter(is_superuser=True)
    if user.exists():
        user = user.first()
    else:
        user = User.objects.create(
            username='soc_su', email='soc_su@phsa.ca',
            password='soc_su_password', is_active=True, is_staff=True,
            is_superuser=True)
        user.set_password('soc_su_password')
        user.save()

    for subscription in subscriptions:
        subscription.update(dict(created_by_id=user.id, updated_by_id=user.id))
        subscription_instance = subscription_model(**subscription)
        subscription_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0030_subscription_failed_events'),
    ]

    operations = [
        migrations.RunPython(add_subscriptions,
                             reverse_code=migrations.RunPython.noop)
    ]
