# Generated by Django 2.2.6 on 2020-01-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0037_merge_20190819_1311'),
        ('mail_collector', '0027_beat_exc_evnts_site'),
        ('mail_collector', '0040_add_subscription_unconfig_bots'),
        ('mail_collector', '0041_auto_20191113_1050'),
    ]

    operations = [
    ]
