# Generated by Django 2.2.6 on 2020-02-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0042_merge_20200121_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainaccount',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='If set, then this row will be preferred by the application. Note there can only be one default row in the table.', verbose_name='Default Instance'),
        ),
        migrations.AlterField(
            model_name='exchangeconfiguration',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='If set, then this row will be preferred by the application. Note there can only be one default row in the table.', verbose_name='Default Instance'),
        ),
    ]
