# Generated by Django 2.2.6 on 2020-03-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0043_auto_20200212_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailhost',
            options={'get_latest_by': '-exchange_last_seen', 'ordering': ['-exchange_last_seen'], 'verbose_name': 'Exchange Monitoring Bot', 'verbose_name_plural': 'Exchange Monitoring Bots'},
        ),
        migrations.AlterModelOptions(
            name='mailsite',
            options={'get_latest_by': '-winlogbeathost__exchange_last_seen', 'ordering': ['-winlogbeathost__exchange_last_seen'], 'verbose_name': 'Exchange Monitoring Site', 'verbose_name_plural': 'Exchange Monitoring Sites'},
        ),
        migrations.AlterField(
            model_name='mailbotlogevent',
            name='source_host',
            field=models.ForeignKey(limit_choices_to={'exchange_last_seen__isnull': False}, on_delete=django.db.models.deletion.PROTECT, to='citrus_borg.WinlogbeatHost', verbose_name='Event Source Host'),
        ),
    ]
