# Generated by Django 2.2.6 on 2020-10-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0045_auto_20200420_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainaccount',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='exchangeaccount',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='exchangeconfiguration',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='exchangeserver',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='mailbetweendomains',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='witnessemail',
            old_name='created_on',
            new_name='created',
        ),
    ]
