# Generated by Django 2.2.6 on 2021-02-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0047_auto_20210218_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbotlogevent',
            options={'get_latest_by': 'event_registered_on', 'ordering': ['-event_group_id', 'mail_account', 'event_type_sort'], 'verbose_name': 'Mail Monitoring Event', 'verbose_name_plural': 'Mail Monitoring Events'},
        ),
    ]
