# Generated by Django 2.2.6 on 2021-03-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0048_auto_20210219_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbotmessage',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='mailbotmessage',
            name='received_from',
        ),
    ]
