# Generated by Django 2.2.6 on 2021-03-15 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import p_soc_auto_base.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_collector', '0049_auto_20210305_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangedatabase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='object creation time stamp', verbose_name='created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangedatabase',
            name='created_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='mail_collector_exchangedatabase_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='exchangedatabase',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='exchangedatabase',
            name='updated_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='mail_collector_exchangedatabase_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='exchangedatabase',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='exchangeserver',
            name='last_send',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time a message was sent via this server', null=True, verbose_name='Last Send'),
        ),
    ]
