# Generated by Django 2.2.6 on 2021-04-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0050_auto_20210315_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbotlogevent',
            name='event_group_id',
            field=models.CharField(blank=True, help_text='Deprecated', max_length=128, null=True, verbose_name='Session Id'),
        ),
    ]
