# Generated by Django 2.2.6 on 2021-04-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0051_auto_20210429_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbotlogevent',
            options={'get_latest_by': 'event_registered_on', 'ordering': ['-site', 'mail_account', 'event_type_sort'], 'verbose_name': 'Mail Monitoring Event', 'verbose_name_plural': 'Mail Monitoring Events'},
        ),
        migrations.AlterModelOptions(
            name='mailbotmessage',
            options={'get_latest_by': '-event__event_registered_on', 'ordering': ['-event__site', 'sent_from', 'event__event_type_sort'], 'verbose_name': 'Mail Monitoring Message', 'verbose_name_plural': 'Mail Monitoring Messages'},
        ),
        migrations.RemoveField(
            model_name='mailbotlogevent',
            name='event_group_id',
        ),
        migrations.AddField(
            model_name='mailbotlogevent',
            name='site',
            field=models.CharField(blank=True, help_text='The site the message was sent from', max_length=128, null=True, verbose_name='Session Id'),
        ),
    ]
