# Generated by Django 2.2.6 on 2021-05-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0052_auto_20210429_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbotlogevent',
            options={'get_latest_by': 'event_registered_on', 'ordering': ['-event_group_id', 'mail_account', 'event_type_sort'], 'verbose_name': 'Mail Monitoring Event', 'verbose_name_plural': 'Mail Monitoring Events'},
        ),
        migrations.AlterModelOptions(
            name='mailbotmessage',
            options={'get_latest_by': '-event__event_registered_on', 'ordering': ['-event__event_group_id', 'sent_from', 'event__event_type_sort'], 'verbose_name': 'Mail Monitoring Message', 'verbose_name_plural': 'Mail Monitoring Messages'},
        ),
        migrations.RemoveField(
            model_name='mailbotlogevent',
            name='site',
        ),
        migrations.AddField(
            model_name='mailbotlogevent',
            name='event_group_id',
            field=models.CharField(db_index=True, default=0, help_text='Identifier for a group of related exchange client events', max_length=128, verbose_name='Session Id'),
            preserve_default=False,
        ),
    ]
