# Generated by Django 2.2.6 on 2019-11-13 20:24
from django.contrib.auth.models import User, UserManager

from django.db import migrations


def populate_ac_orion_nodes(apps, schema_editor):

    user = User.objects.filter(is_superuser=True)
    if user.exists():
        user = user.first()
    else:
        user = User.objects.create(
            username='soc_su', email='soc_su@phsa.ca',
            password='soc_su_password', is_active=True, is_staff=True,
            is_superuser=True)
        user.set_password('soc_su_password')
        user.save()

    ldap_bind_cred = apps.get_model(
        'ldap_probe', 'LDAPBindCred').objects.filter(is_default=True).get()

    orion_nodes = apps.get_model(
        'orion_integration', 'OrionDomainControllerNode').objects.\
        filter(node__program_application_type='DomainController').all()

    ac_nodes_model = apps.get_model('ldap_probe', 'OrionADNode')

    for node in orion_nodes:
        ac_node = ac_nodes_model(
            node=node, ldap_bind_cred=ldap_bind_cred,
            created_by_id=user.id, updated_by_id=user.id)
        ac_node.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0002_populate_ldap_bind_creds'),
    ]

    operations = [
        migrations.RunPython(populate_ac_orion_nodes,
                             reverse_code=migrations.RunPython.noop)
    ]
