# Generated by Django 2.2.6 on 2019-11-13 21:43
from django.contrib.auth.models import User, UserManager

from django.db import migrations


def populate_ac_nodes(apps, schema_editor):

    user = User.objects.filter(is_superuser=True)
    if user.exists():
        user = user.first()
    else:
        user = User.objects.create(
            username='soc_su', email='soc_su@phsa.ca',
            password='soc_su_password', is_active=True, is_staff=True,
            is_superuser=True)
        user.set_password('soc_su_password')
        user.save()

    ldap_bind_cred = apps.get_model(
        'ldap_probe', 'LDAPBindCred').objects.filter(is_default=True).get()

    ac_nodes = [
        'alpha.fraserhealth.org', 'atlas.fraserhealth.org',
        'blackcomb.fraserhealth.org', 'cypress.fraserhealth.org',
        'dcns0002.fraserhealth.org', 'dcns0004.fraserhealth.org',
        'denman.fraserhealth.org ', 'everest.fraserhealth.org',
        'fuji.fraserhealth.org ', 'janus.fraserhealth.org',
        'laila.fraserhealth.org ', 'olympus.fraserhealth.org',
        'phcdc3.phcnet.ca', 'phcdc5.phcnet.ca', 'phcdc7.phcnet.ca',
        'phcdc21.phcnet.ca', 'phcdc41.phcnet.ca', 'phcdc42.phcnet.ca',
        'phsacdcldcphc3.phcnet.ca', 'phsacdcldcphc4.phcnet.ca',
        'phsacdcldcphsa3.phsabc.ehcnet.ca',
        'phsacdcldcphsa4.phsabc.ehcnet.ca', 'phsacdcldcvch3.vch.ca',
        'phsacdcldcvch4.vch.ca', 'phsacdcldcvrhb3.main.vrhb.local',
        'phsacdcldcvrhb4.main.vrhb.local', 'proteus.fraserhealth.org',
        'rainier.fraserhealth.org', 'rhsdc2.main.vrhb.local',
        'robson.fraserhealth.org', 'rootdc4.vrhb.local', 'rootdc5.vrhb.local',
        'rootdc6.vrhb.local', 'spdc0001.healthbc.org',
        'spdc0002.healthbc.org', 'spdc0003.healthbc.org',
        'spdc0004.healthbc.org', 'spdc0005.healthbc.org',
        'spdc0006.healthbc.org', 'spdc0007.healthbc.org',
        'spdc0008.healthbc.org', 'spdc0009.healthbc.org',
        'spdc0010.healthbc.org', 'spdc0011.healthbc.org',
        'spdc0012.healthbc.org', 'spdc0013.healthbc.org',
        'spdc0014.healthbc.org', 'spdc0015.healthbc.org',
        'spdc0016.healthbc.org', 'spdc0017.healthbc.org',
        'spdcphc001.phcnet.ca', 'spdcphsa001.phsabc.ehcnet.ca',
        'spdcvrhb006.main.vrhb.local', 'srvcs01.phsabc.ehcnet.ca',
        'srvcs02.phsabc.ehcnet.ca', 'srvcs03.phsabc.ehcnet.ca',
        'srvcs04.phsabc.ehcnet.ca', 'srvcs41.phsabc.ehcnet.ca',
        'srvfr01.ehcnet.ca', 'srvfr02.ehcnet.ca', 'srvpngcs01.phsapng.ca',
        'srvpngcs02.phsapng.ca', 'svmcs06.phsabc.ehcnet.ca',
        'svmcs10.phsabc.ehcnet.ca', 'svmcs15-new.phsabc.ehcnet.ca',
        'svmcs15.phsabc.ehcnet.ca', 'svmcs16-new.phsabc.ehcnet.ca',
        'svmcs16.phsabc.ehcnet.ca', 'svmfr03.ehcnet.ca', 'vchdc1.vch.ca',
        'vchdc2.vch.ca', 'vchdc3.vch.ca', 'vchdc4.vch.ca', 'vchdc5.vch.ca',
        'vchdc6.vch.ca', 'vchdc7.vch.ca', 'vchdc8.vch.ca', 'vchdc9.vch.ca',
        'vchdc12.vch.ca', 'vchdc13.vch.ca', 'vchdc14.vch.ca',
        'vchdc16.vch.ca', 'vchdc41.vch.ca', 'vesuvius.fraserhealth.org ',
        'vrhbdc5.main.vrhb.local', 'vrhbdc6.main.vrhb.local',
        'vrhbdc7.main.vrhb.local', 'vrhbdc41.main.vrhb.local',
        'whistler.fraserhealth.org', 'whitney.fraserhealth.org',
    ]

    ac_nodes_model = apps.get_model('ldap_probe', 'NonOrionADNode')

    for node_dns in ac_nodes:
        ac_node = ac_nodes_model(
            node_dns=node_dns, ldap_bind_cred=ldap_bind_cred,
            created_by_id=user.id, updated_by_id=user.id)
        ac_node.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0003_populate_ac_orion_node'),
    ]

    operations = [
        migrations.RunPython(populate_ac_nodes,
                             reverse_code=migrations.RunPython.noop)
    ]
