# Generated by Django 2.2.6 on 2019-11-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0005_auto_20191115_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldapcrederror',
            old_name='short_descriptiom',
            new_name='short_description',
        ),
    ]
