# Generated by Django 2.2.6 on 2019-11-18 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0006_auto_20191118_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapprobelog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='object creation time stamp', verbose_name='created on'),
            preserve_default=False,
        ),
    ]
