# Generated by Django 2.2.6 on 2019-11-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0008_ldapprobelog_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapprobelog',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Probe data has expired'),
        ),
    ]
