# Generated by Django 2.2.6 on 2019-11-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0009_ldapprobelog_is_expired'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonorionadnode',
            options={'get_latest_by': 'updated_on', 'ordering': ['node_dns'], 'verbose_name': 'Domain Controller not present in Orion', 'verbose_name_plural': 'Domain Controllers not present in Orion'},
        ),
    ]
