# Generated by Django 2.2.6 on 2019-11-22 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0011_auto_20191122_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapcrederror',
            options={'ordering': ['error_unique_identifier'], 'verbose_name': 'Active Directory Bind Error', 'verbose_name_plural': 'Common Active Directory Bind Errors'},
        ),
    ]
