# Generated by Django 2.2.6 on 2019-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0014_auto_20191125_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapprobelog',
            name='elapsed_anon_bind',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='LDAP anonymous bind duration'),
        ),
        migrations.AlterField(
            model_name='ldapprobelog',
            name='elapsed_bind',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='LDAP bind duration'),
        ),
        migrations.AlterField(
            model_name='ldapprobelog',
            name='elapsed_initialize',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='LDAP initialization duration'),
        ),
        migrations.AlterField(
            model_name='ldapprobelog',
            name='elapsed_read_root',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='LDAP read root DSE duration'),
        ),
        migrations.AlterField(
            model_name='ldapprobelog',
            name='elapsed_search_ext',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='LDAP extended search duration'),
        ),
    ]
