# Generated by Django 2.2.6 on 2019-11-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0016_auto_20191126_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionadnode',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orion_integration.OrionDomainControllerNode', verbose_name='Orion Node for Domain Controller'),
        ),
    ]
