# Generated by Django 2.2.6 on 2019-11-27 23:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0019_ldapprobelog_failed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapProbeLogFailed',
            fields=[
            ],
            options={
                'verbose_name': 'Failed AD service probe',
                'verbose_name_plural': 'Failed AD service probes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ldap_probe.ldapprobelog',),
            managers=[
                ('obejcts', django.db.models.manager.Manager()),
            ],
        ),
    ]
