# Generated by Django 2.2.6 on 2019-12-19 21:09

from django.db import migrations, models
from ldap_probe.models import _get_default_alert_threshold, _get_default_warn_threshold, _get_default_err_threshold


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0033_auto_20191217_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnodeperfbucket',
            name='alert_threshold',
            field=models.DecimalField(db_index=True, decimal_places=3, default=_get_default_alert_threshold, help_text='If the AD services response time for any probe is worse than this value, raise an immediate alert.', max_digits=4, verbose_name='Alert Response Time Threshold'),
        ),
        migrations.AlterField(
            model_name='adnodeperfbucket',
            name='avg_err_threshold',
            field=models.DecimalField(db_index=True, decimal_places=3, default=_get_default_err_threshold, help_text='If the average AD services response time is worse than this value, include this node in the periodic performance degradation errors report.', max_digits=4, verbose_name='Error Response Time Threshold'),
        ),
        migrations.AlterField(
            model_name='adnodeperfbucket',
            name='avg_warn_threshold',
            field=models.DecimalField(db_index=True, decimal_places=3, default=_get_default_warn_threshold, help_text='If the average AD services response time is worse than this value, include this node in the periodic performance degradation warnings report.', max_digits=4, verbose_name='Warning Response Time Threshold'),
        ),
        migrations.AlterField(
            model_name='adnodeperfbucket',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='If set, then this row will be preferred by the application. Note there can only be one default row in the table.', verbose_name='Default Instance'),
        ),
        migrations.AlterField(
            model_name='ldapbindcred',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='If set, then this row will be preferred by the application. Note there can only be one default row in the table.', verbose_name='Default Instance'),
        ),
    ]
