# Generated by Django 2.2.6 on 2019-12-24 19:19

from django.db import migrations


def del_old_subs(apps, schema_editor):
    subscriptions = [
        'LDAP: summary report, anonymous bind, perf, non orion',
        'LDAP: summary report, anonymous bind, perf, orion',
        'LDAP: summary report, full bind, perf, non orion',
        'LDAP: summary report, full bind, perf, orion',
    ]

    subscription_model = apps.get_model('ssl_cert_tracker', 'subscription')

    subscription_model.objects.filter(
        subscription__in=subscriptions).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0036_subs_perf_reps'),
    ]

    operations = [
        migrations.RunPython(del_old_subs,
                             reverse_code=migrations.RunPython.noop)
    ]
