# Generated by Django 2.2.6 on 2020-01-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0041_add_perf_buckets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adnodeperfbucket',
            old_name='location',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nonorionadnode',
            old_name='location',
            new_name='performance_bucket',
        ),
        migrations.RenameField(
            model_name='orionadnode',
            old_name='location',
            new_name='performance_bucket',
        ),
    ]
