# Generated by Django 2.2.6 on 2020-01-02 22:22
from django.contrib.auth.models import User
from django.db import migrations

from p_soc_auto_base.utils import get_or_create_user


def delete_perf_buckets(apps, schema_editor):
    perf_bucket_model = apps.get_model('ldap_probe', 'ADNodePerfBucket')
    perf_bucket_model.objects.filter(is_default=True).update(is_default=False)
    perf_bucket_model.objects.all().delete()


def add_new_perf_buckets(apps, schema_editor):
    user = get_or_create_user()

    user_dict = {'created_by_id': user.id, 'updated_by_id': user.id, }

    perf_buckets = [{
        'name':               'Alert at 10 ms',
        'avg_warn_threshold': .0025,
        'avg_err_threshold':  .005,
        'alert_threshold':    .01,
        'notes':              '',
        'is_default':         False,
    }, {
        'name':               'Alert at 100 ms',
        'avg_warn_threshold': .025,
        'avg_err_threshold':  .05,
        'alert_threshold':    .1,
        'notes':              '',
        'is_default':         True,
    }, {
        'name':               'Alert at 1 s',
        'avg_warn_threshold': .25,
        'avg_err_threshold':  .5,
        'alert_threshold':    1,
        'notes':              '',
        'is_default':         False,
    },  {
        'name': 'Alert at 10 s',
        'avg_warn_threshold': 2.5,
        'avg_err_threshold': 5,
        'alert_threshold': 10,
        'notes': '',
        'is_default': False,
    }, ]

    perf_bucket_model = apps.get_model('ldap_probe', 'ADNodePerfBucket')
    for perf_bucket_dict in perf_buckets:
        perf_bucket_dict.update(user_dict)
        perf_bucket = perf_bucket_model(**perf_bucket_dict)
        perf_bucket.save()


class Migration(migrations.Migration):
    dependencies = [('ldap_probe', '0043_auto_20200103_1141'), ]

    operations = [migrations.RunPython(delete_perf_buckets,
                                       reverse_code=migrations.RunPython.noop),
                  migrations.RunPython(add_new_perf_buckets,
                                       reverse_code=migrations.RunPython.noop)]
