# Generated by Django 2.2.6 on 2020-01-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0041_add_perf_buckets'),
        ('ldap_probe', '0007_populate_ldap_errors'),
        ('ldap_probe', '0037_delete_old_perf_subs'),
        ('ldap_probe', '0045_add_dcs_to_buckets'),
    ]

    operations = [
    ]
