# Generated by Django 2.2.6 on 2020-04-20 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import p_soc_auto_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ldap_probe', '0048_auto_20200123_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnodeperfbucket',
            name='created_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='ldap_probe_adnodeperfbucket_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='adnodeperfbucket',
            name='updated_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='ldap_probe_adnodeperfbucket_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='ldapbindcred',
            name='created_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='ldap_probe_ldapbindcred_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='ldapbindcred',
            name='updated_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='ldap_probe_ldapbindcred_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='ldapcrederror',
            name='created_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='ldap_probe_ldapcrederror_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='ldapcrederror',
            name='updated_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='ldap_probe_ldapcrederror_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='nonorionadnode',
            name='created_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='ldap_probe_nonorionadnode_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='nonorionadnode',
            name='updated_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='ldap_probe_nonorionadnode_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='orionadnode',
            name='created_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='ldap_probe_orionadnode_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='orionadnode',
            name='updated_by',
            field=models.ForeignKey(default=p_soc_auto_base.utils.get_default_user_id, on_delete=django.db.models.deletion.PROTECT, related_name='ldap_probe_orionadnode_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
