# Generated by Django 2.1 on 2018-08-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCertsRule',
            fields=[
                ('recid', models.AutoField(primary_key=True, serialize=False)),
                ('intervals', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
