# Generated by Django 2.0.7 on 2018-08-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orionnodestatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orionnodestatus',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='orionnode',
            options={'verbose_name': 'Orion Node', 'verbose_name_plural': 'Orion Nodes'},
        ),
        migrations.AddField(
            model_name='orionnode',
            name='details_url',
            field=models.TextField(blank=True, null=True, verbose_name='Node Details URL'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='status_orion_id',
            field=models.BigIntegerField(db_index=True, default=0, help_text='This will probably changes but that is how they do it for the moment; boohoo', verbose_name='Orion Node Status Id'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='status',
            field=models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Node Status'),
        ),
        migrations.DeleteModel(
            name='OrionNodeStatus',
        ),
    ]
