# Generated by Django 2.0.7 on 2018-08-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionnode',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, protocol='IPv4', unique=True, verbose_name='IP Address'),
        ),
    ]
