# Generated by Django 2.0.7 on 2018-08-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0002_auto_20180813_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionnode',
            name='status',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Node Status'),
        ),
    ]
