# Generated by Django 2.0.7 on 2018-08-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0002_auto_20180814_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionnode',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, protocol='IPv4', verbose_name='IP Address'),
        ),
    ]
