# Generated by Django 2.0.7 on 2018-08-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0003_auto_20180813_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionnode',
            name='node_caption',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Node Caption'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='node_name',
            field=models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Node Name'),
        ),
    ]
