# Generated by Django 2.0.7 on 2018-08-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0003_auto_20180814_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='orionnode',
            name='sensor',
            field=models.CharField(db_index=True, default='ICMP', help_text='Maps to Orion.Nodes.ObjectSubtype', max_length=16, verbose_name='Sensor'),
        ),
        migrations.AlterUniqueTogether(
            name='orionnode',
            unique_together={('sensor', 'ip_address')},
        ),
    ]
