# Generated by Django 2.0.7 on 2018-08-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0004_auto_20180814_1720'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orionnode',
            unique_together=set(),
        ),
    ]
