# Generated by Django 2.0.7 on 2018-08-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0004_auto_20180813_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionnode',
            name='node_name',
            field=models.CharField(db_index=True, max_length=254, verbose_name='Node Name'),
        ),
    ]
