# Generated by Django 2.0.7 on 2018-08-14 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orion_integration', '0005_auto_20180814_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrionAPMApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('orion_id', models.BigIntegerField(db_index=True, help_text='Use the value in this field to query the Orion server', unique=True, verbose_name='Orion Object Id')),
                ('application_name', models.CharField(db_index=True, help_text='The application name as reported by Orion.APM.Application', max_length=254, verbose_name='Application Name')),
                ('details_url', models.TextField(blank=True, null=True, verbose_name='Application Details URL')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Application Fully Qualified Name')),
                ('status', models.CharField(db_index=True, max_length=254, verbose_name='Node Status')),
                ('status_orion_id', models.BigIntegerField(db_index=True, default=0, help_text='This will probably changes but that is how they do it for the moment; boohoo', verbose_name='Orion Node Status Id')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orion_integration_orionapmapplication_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('node', models.ForeignKey(help_text='The node where the application is running', on_delete=django.db.models.deletion.CASCADE, to='orion_integration.OrionNode', verbose_name='Orion Node')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orion_integration_orionapmapplication_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Orion Application',
                'verbose_name_plural': 'Orion Applications',
            },
        ),
    ]
