# Generated by Django 2.0.7 on 2018-08-30 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0006_orionapmapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrionCSTNode',
            fields=[
                ('orionnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orion_integration.OrionNode')),
            ],
            options={
                'verbose_name': 'Orion Cerner CST Node',
                'verbose_name_plural': 'Orion Cerner CST Nodes',
            },
            bases=('orion_integration.orionnode', models.Model),
        ),
        migrations.AlterField(
            model_name='orionapmapplication',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='orionnodecategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on'),
        ),
    ]
