# Generated by Django 2.0.7 on 2018-08-31 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0006_orionapmapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='orionnode',
            name='address',
            field=models.CharField(db_index=True, default='bogus', max_length=254, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orionnode',
            name='building',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='city',
            field=models.CharField(db_index=True, default='bogus', max_length=64, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orionnode',
            name='closet',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Closet'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='device_type',
            field=models.CharField(db_index=True, default='bogus', max_length=64, verbose_name='Device Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orionnode',
            name='ha',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='HA'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='hardware_incident_status',
            field=models.TextField(blank=True, null=True, verbose_name='Hardware Incident Status'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='incident_status',
            field=models.TextField(blank=True, null=True, verbose_name='Incident Status'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='make',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Make'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='node_owner',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Node Owner'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='out_of_band',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='out of band'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='program_application',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='program application'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='program_application_type',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='program application type'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='provider',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='site',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='site'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='site_contact_name',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='site contact name'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='site_hours',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='site hours'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='site_phone',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='site phone'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='site_type',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='site type'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='wan_bandwidth',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='WAN bandwidth'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='wan_node',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='WAN node'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='wan_provider',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='WAN provider'),
        ),
        migrations.AlterField(
            model_name='orionapmapplication',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orion_integration.OrionNodeCategory', verbose_name='Orion Node Category'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='orionnodecategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on'),
        ),
    ]
