# Generated by Django 2.0.7 on 2018-08-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0006_orionapmapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionapmapplication',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='orionnodecategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on'),
        ),
    ]
