# Generated by Django 2.0.7 on 2018-08-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0007_auto_20180831_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionnode',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='out_of_band',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='out of band'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='wan_provider',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='WAN provider'),
        ),
    ]
