# Generated by Django 2.0.7 on 2018-08-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0008_auto_20180831_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orionnode',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='device_type',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='site_hours',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='site hours'),
        ),
        migrations.AlterField(
            model_name='orionnode',
            name='wan_provider',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='WAN provider'),
        ),
    ]
