# Generated by Django 2.0.7 on 2018-09-04 16:30

from django.db import migrations


def remove_heart_beat_task(apps, schema_editor):
    model = apps.get_model('django_celery_beat', 'PeriodicTask')
    qs = model.objects.filter(task__exact='orion_integration.tasks.heart_beat')
    if qs.exists():
        qs.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0009_auto_20180831_2129'),
    ]

    operations = [
        migrations.RunPython(remove_heart_beat_task,
                             reverse_code=migrations.RunPython.noop)
    ]
