# Generated by Django 2.1.1 on 2018-09-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0010_remove_heart_beat_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrionCernerCSTNode',
            fields=[
            ],
            options={
                'verbose_name': 'Orion Cerner CST Node',
                'verbose_name_plural': 'Orion Cerner CST Nodes',
                'proxy': True,
                'indexes': [],
            },
            bases=('orion_integration.orionnode',),
        ),
        migrations.AddField(
            model_name='orionapmapplication',
            name='not_seen_since',
            field=models.DateTimeField(blank=True, db_index=True, help_text='populated if this Orion entity is not available anymore on the Orion server', null=True, verbose_name='Not Seen Since'),
        ),
        migrations.AddField(
            model_name='orionnode',
            name='not_seen_since',
            field=models.DateTimeField(blank=True, db_index=True, help_text='populated if this Orion entity is not available anymore on the Orion server', null=True, verbose_name='Not Seen Since'),
        ),
        migrations.AddField(
            model_name='orionnodecategory',
            name='not_seen_since',
            field=models.DateTimeField(blank=True, db_index=True, help_text='populated if this Orion entity is not available anymore on the Orion server', null=True, verbose_name='Not Seen Since'),
        ),
    ]
