# Generated by Django 2.2.6 on 2019-11-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0013_auto_20180918_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrionDomainControllerNode',
            fields=[
            ],
            options={
                'verbose_name': 'Windows domain controller',
                'verbose_name_plural': 'Windows domain controllers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orion_integration.orionnode',),
        ),
    ]
