# Generated by Django 2.2.6 on 2020-01-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0014_oriondomaincontrollernode'),
        ('orion_integration', '0010_remove_heart_beat_task'),
    ]

    operations = [
    ]
