# Generated by Django 2.2.6 on 2020-01-17 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ('orion_integration', '0001_initial'),
        ('orion_integration', '0002_auto_20180814_1707'),
        ('orion_integration', '0003_auto_20180814_1714'),
        ('orion_integration', '0004_auto_20180814_1720'),
        ('orion_integration', '0005_auto_20180814_1747'),
        ('orion_integration', '0006_orionapmapplication'),
        ('orion_integration', '0007_auto_20180831_2113'),
        ('orion_integration', '0008_auto_20180831_2122'),
        ('orion_integration', '0009_auto_20180831_2129'),
        ('orion_integration', '0011_auto_20180905_2208'),
        ('orion_integration', '0012_auto_20180917_2152'),
        ('orion_integration', '0013_auto_20180918_2028'),
        ('orion_integration', '0014_oriondomaincontrollernode'),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrionNodeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('orion_id', models.BigIntegerField(db_index=True, help_text='Use the value in this field to query the Orion server', unique=True, verbose_name='Orion Object Id')),
                ('not_seen_since', models.DateTimeField(blank=True, db_index=True, help_text='populated if this Orion entity is not available anymore on the Orion server', null=True, verbose_name='Not Seen Since')),
                ('category', models.CharField(db_index=True, help_text='Orion Node Category Help', max_length=254, unique=True, verbose_name='Orion Node Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orion_integration_orionnodecategory_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orion_integration_orionnodecategory_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Orion Node Category',
                'verbose_name_plural': 'Orion Node Categories',
            },
        ),
        migrations.CreateModel(
            name='OrionNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('orion_id', models.BigIntegerField(db_index=True, help_text='Use the value in this field to query the Orion server', unique=True, verbose_name='Orion Object Id')),
                ('not_seen_since', models.DateTimeField(blank=True, db_index=True, help_text='populated if this Orion entity is not available anymore on the Orion server', null=True, verbose_name='Not Seen Since')),
                ('address', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Address')),
                ('building', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Building')),
                ('city', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='City')),
                ('closet', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Closet')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Device Type')),
                ('ha', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='HA')),
                ('hardware_incident_status', models.TextField(blank=True, null=True, verbose_name='Hardware Incident Status')),
                ('incident_status', models.TextField(blank=True, null=True, verbose_name='Incident Status')),
                ('make', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Make')),
                ('node_owner', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Node Owner')),
                ('out_of_band', models.CharField(blank=True, max_length=64, null=True, verbose_name='out of band')),
                ('program_application', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='program application')),
                ('program_application_type', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='program application type')),
                ('provider', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='provider')),
                ('region', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='region')),
                ('site', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='site')),
                ('site_contact_name', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='site contact name')),
                ('site_hours', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='site hours')),
                ('site_phone', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='site phone')),
                ('site_type', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='site type')),
                ('wan_bandwidth', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='WAN bandwidth')),
                ('wan_node', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='WAN node')),
                ('wan_provider', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='WAN provider')),
                ('node_caption', models.CharField(db_index=True, max_length=254, verbose_name='Node Caption')),
                ('sensor', models.CharField(db_index=True, default='ICMP', help_text='Maps to Orion.Nodes.ObjectSubtype', max_length=16, verbose_name='Sensor')),
                ('ip_address', models.GenericIPAddressField(db_index=True, protocol='IPv4', verbose_name='IP Address')),
                ('node_name', models.TextField(verbose_name='Node Name')),
                ('node_dns', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='DNS')),
                ('node_description', models.TextField(verbose_name='Orion Node Description')),
                ('vendor', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Vendor')),
                ('location', models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Location')),
                ('machine_type', models.CharField(blank=True, db_index=True, help_text='this needs to become a foreign key', max_length=254, null=True, verbose_name='Machine Type')),
                ('status', models.CharField(db_index=True, max_length=254, verbose_name='Node Status')),
                ('status_orion_id', models.BigIntegerField(db_index=True, default=0, help_text='This will probably changes but that is how they do it for the moment; boohoo', verbose_name='Orion Node Status Id')),
                ('details_url', models.TextField(blank=True, null=True, verbose_name='Node Details URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orion_integration.OrionNodeCategory', verbose_name='Orion Node Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orion_integration_orionnode_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orion_integration_orionnode_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Orion Node',
                'verbose_name_plural': 'Orion Nodes',
            },
        ),
        migrations.CreateModel(
            name='OrionAPMApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('orion_id', models.BigIntegerField(db_index=True, help_text='Use the value in this field to query the Orion server', unique=True, verbose_name='Orion Object Id')),
                ('not_seen_since', models.DateTimeField(blank=True, db_index=True, help_text='populated if this Orion entity is not available anymore on the Orion server', null=True, verbose_name='Not Seen Since')),
                ('application_name', models.CharField(db_index=True, help_text='The application name as reported by Orion.APM.Application', max_length=254, verbose_name='Application Name')),
                ('details_url', models.TextField(blank=True, null=True, verbose_name='Application Details URL')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Application Fully Qualified Name')),
                ('status', models.CharField(db_index=True, max_length=254, verbose_name='Node Status')),
                ('status_orion_id', models.BigIntegerField(db_index=True, default=0, help_text='This will probably changes but that is how they do it for the moment; boohoo', verbose_name='Orion Node Status Id')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orion_integration_orionapmapplication_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('node', models.ForeignKey(help_text='The node where the application is running', on_delete=django.db.models.deletion.CASCADE, to='orion_integration.OrionNode', verbose_name='Orion Node')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orion_integration_orionapmapplication_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Orion Application',
                'verbose_name_plural': 'Orion Applications',
            },
        ),
        migrations.CreateModel(
            name='OrionCernerCSTNode',
            fields=[
            ],
            options={
                'verbose_name': 'Orion Cerner CST Node',
                'verbose_name_plural': 'Orion Cerner CST Nodes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orion_integration.orionnode',),
        ),
        migrations.CreateModel(
            name='OrionDomainControllerNode',
            fields=[
            ],
            options={
                'verbose_name': 'Windows domain controller',
                'verbose_name_plural': 'Windows domain controllers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orion_integration.orionnode',),
        ),
    ]
