# Generated by Django 2.2.6 on 2021-02-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orion_integration', '0017_auto_20201027_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orionnode',
            options={'get_latest_by': 'updated_on', 'verbose_name': 'Orion Node', 'verbose_name_plural': 'Orion Nodes'},
        ),
    ]
