# Generated by Django 2.1.1 on 2018-11-22 23:06

from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import User


def populate_windows_logs(apps, schema_editor):
    model = apps.get_model('citrus_borg', 'WindowsLog')

    user = User.objects.filter(username=settings.CITRUS_BORG_SERVICE_USER)
    if user.exists():
        user = user.get()
    else:
        user = User.objects.create_user(settings.CITRUS_BORG_SERVICE_USER)

    winlog = model(log_name='Application')
    winlog.created_by_id = user.id
    winlog.updated_by_id = user.id

    winlog.save()


def reverse_this(apps, schema_editor):
    model = apps.get_model('citrus_borg', 'WindowsLog')

    model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0003_populate_event_sources'),
    ]

    operations = [
        migrations.RunPython(populate_windows_logs, reverse_code=reverse_this)
    ]
