# Generated by Django 2.1.1 on 2018-11-26 22:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citrus_borg', '0004_populate_windows_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorgSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('site', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='site name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_borgsite_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_borgsite_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Citrix Bot Site',
                'verbose_name_plural': 'Citrix Bot Sites',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBorgSite',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('site', models.CharField(db_index=True, max_length=64, verbose_name='site name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Citrix Bot Site',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalknownbrokeringdevice',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 11, 26, 22, 22, 16, 969731, tzinfo=utc), verbose_name='last seen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalwinlogbeathost',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 11, 26, 22, 22, 28, 879471, tzinfo=utc), verbose_name='last seen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knownbrokeringdevice',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 11, 26, 22, 22, 42, 112857, tzinfo=utc), verbose_name='last seen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winlogbeathost',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 11, 26, 22, 22, 51, 680728, tzinfo=utc), verbose_name='last seen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalwinlogbeathost',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='citrus_borg.BorgSite'),
        ),
        migrations.AddField(
            model_name='winlogbeathost',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citrus_borg.BorgSite'),
        ),
    ]
