# Generated by Django 2.1.1 on 2018-12-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0005_auto_20181126_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorgSiteNotSeen',
            fields=[
            ],
            options={
                'verbose_name': 'Citrix Bot Site',
                'verbose_name_plural': 'Citrix Bot Sites not seen for at least 72 hours',
                'ordering': ('-winlogbeathost__last_seen',),
                'proxy': True,
                'indexes': [],
            },
            bases=('citrus_borg.borgsite',),
        ),
        migrations.CreateModel(
            name='KnownBrokeringDeviceNotSeen',
            fields=[
            ],
            options={
                'verbose_name': 'Citrix App Server',
                'verbose_name_plural': 'Citrix App Servers not seen for at least 24 hours',
                'proxy': True,
                'indexes': [],
            },
            bases=('citrus_borg.knownbrokeringdevice',),
        ),
        migrations.CreateModel(
            name='WinlogbeatHostNotSeen',
            fields=[
            ],
            options={
                'verbose_name': 'Citrix Bot',
                'verbose_name_plural': 'Citrix Bots not seen for at least 72 hours',
                'proxy': True,
                'indexes': [],
            },
            bases=('citrus_borg.winlogbeathost',),
        ),
        migrations.AlterModelOptions(
            name='historicalknownbrokeringdevice',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Citrix App Server'},
        ),
        migrations.AlterModelOptions(
            name='knownbrokeringdevice',
            options={'verbose_name': 'Citrix App Server', 'verbose_name_plural': 'Citrix App Servers'},
        ),
        migrations.AlterField(
            model_name='historicalknownbrokeringdevice',
            name='broker_name',
            field=models.CharField(db_index=True, help_text='the name of a Citrix session server that has serviced at least one request', max_length=15, verbose_name='server name'),
        ),
        migrations.AlterField(
            model_name='knownbrokeringdevice',
            name='broker_name',
            field=models.CharField(db_index=True, help_text='the name of a Citrix session server that has serviced at least one request', max_length=15, unique=True, verbose_name='server name'),
        ),
    ]
