# Generated by Django 2.1.1 on 2018-12-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0010_auto_20181205_1248'),
        ('citrus_borg', '0010_auto_20181205_1442'),
    ]

    operations = [
    ]
