# Generated by Django 2.1.1 on 2019-01-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0011_merge_20181205_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='winlogevent',
            name='raw_message',
            field=models.TextField(blank=True, help_text='the application cannot process this message', null=True, verbose_name='Raw Message'),
        ),
    ]
