# Generated by Django 2.1.4 on 2019-03-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0016_auto_20190107_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwinlogbeathost',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalwinlogbeathost',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalwinlogbeathost',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalwinlogbeathost',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='winlogbeathost',
            name='orion_id',
            field=models.BigIntegerField(blank=True, default=0, help_text='Use the value in this field to query the Orion server', null=True, verbose_name='Orion Object Id'),
        ),
        migrations.DeleteModel(
            name='HistoricalWinlogbeatHost',
        ),
    ]
