# Generated by Django 2.1.4 on 2019-03-22 18:04

from django.db import migrations

change_tasks = [
    'citrus_borg.tasks.email_failed_logins_alarm',
    'citrus_borg.tasks.email_dead_servers_alert',
    'citrus_borg.tasks.email_dead_sites_alert',
    'citrus_borg.tasks.email_dead_borgs_alert', ]


def disable_beats(apps, schema_editor):

    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    PeriodicTask.objects.filter(task__in=change_tasks).update(enabled=False)


def enable_beats(apps, schema_editor):

    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    PeriodicTask.objects.filter(task__in=change_tasks).update(enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0018_add_periodic_tasks'),
    ]

    operations = [
        migrations.RunPython(disable_beats,
                             reverse_code=enable_beats)
    ]
