# Generated by Django 2.1.4 on 2019-03-26 22:28

from django.db import migrations


def update_07_crontab(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    periodic_task = PeriodicTask.objects.get(
        task='citrus_borg.tasks.email_sites_login_ux_summary_reports')

    crontab = periodic_task.crontab

    crontab.hour = '07,19'

    crontab.save()


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0019_disable_beats_for_email_alerts'),
    ]

    operations = [
        migrations.RunPython(update_07_crontab,
                             reverse_code=migrations.RunPython.noop)
    ]
