# Generated by Django 2.1.4 on 2019-03-27 16:08

from django.db import migrations


def update_beats(apps, schema_editor):
    update_tasks = ['citrus_borg.tasks.email_dead_borgs_report',
                    'citrus_borg.tasks.email_dead_sites_report',
                    'citrus_borg.tasks.email_dead_servers_report']
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')

    crontab = CrontabSchedule.objects.filter(hour__icontains='07,19',
                                             minute__icontains='00').first()

    PeriodicTask.objects.filter(task__in=update_tasks).update(crontab=crontab)


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0020_change_beat_to_07_19'),
    ]

    operations = [
        migrations.RunPython(update_beats,
                             reverse_code=migrations.RunPython.noop)
    ]
