# Generated by Django 2.1.4 on 2019-03-28 18:48

from django.db import migrations


def fix_beats(apps, schema_editor):
    update_tasks = [
        'citrus_borg.tasks.email_borg_login_summary_report',
    ]

    create_tasks = [
        {
            'name': 'Email Citrix Bot Report for Excessive Logon Response Time Events',
            'task': 'citrus_borg.tasks.email_failed_ux_report',
        },
    ]

    crontab = apps.get_model(
        'django_celery_beat',
        'CrontabSchedule').objects.filter(hour__icontains='07,19',
                                          minute__icontains='00').first()

    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    PeriodicTask.objects.filter(task__in=update_tasks).update(crontab=crontab)

    for task in create_tasks:
        new_task = PeriodicTask(**task)
        new_task.crontab = crontab
        new_task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0021_update_more_beats_to_07_19'),
    ]

    operations = [
        migrations.RunPython(fix_beats,
                             reverse_code=migrations.RunPython.noop)
    ]
