# Generated by Django 2.1.4 on 2019-05-29 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0023_auto_20190527_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='winlogbeathost',
            name='excgh_last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Exchange client bot last seen'),
        ),
        migrations.AlterField(
            model_name='winlogbeathost',
            name='last_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Citrix bot last seen'),
        ),
        migrations.AlterField(
            model_name='winlogevent',
            name='source_host',
            field=models.ForeignKey(limit_choices_to={'last_seen__isnull': False}, on_delete=django.db.models.deletion.PROTECT, to='citrus_borg.WinlogbeatHost', verbose_name='Event Source Host'),
        ),
    ]
