# Generated by Django 2.1.4 on 2019-06-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0024_auto_20190529_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitrixHost',
            fields=[
            ],
            options={
                'verbose_name': 'Citrix Bot',
                'verbose_name_plural': 'Citrix Bots',
                'ordering': ['-last_seen'],
                'get_latest_by': '-last_seen',
                'proxy': True,
                'indexes': [],
            },
            bases=('citrus_borg.winlogbeathost',),
        ),
        migrations.AlterModelOptions(
            name='winlogevent',
            options={'get_latest_by': '-created_on', 'ordering': ['-created_on'], 'verbose_name': 'Citrix Bot Windows Log Event', 'verbose_name_plural': 'Citrix Bot Windows Log Events'},
        ),
    ]
