# Generated by Django 2.2.3 on 2019-08-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0034_auto_20190806_1409'),
        ('citrus_borg', '0025_auto_20190603_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='winlogbeathost',
            name='exchange_client_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_collector.ExchangeConfiguration', verbose_name='Exchange client configuration'),
        ),
    ]
