# Generated by Django 2.2.3 on 2019-08-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0026_winlogbeathost_exchange_client_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winlogbeathost',
            name='exchange_client_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_collector.ExchangeConfiguration', verbose_name='Exchange client configuration'),
        ),
    ]
