# Generated by Django 2.2.6 on 2020-01-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0027_auto_20190819_1308'),
        ('citrus_borg', '0013_add_failed_login_site_report_subscription'),
        ('citrus_borg', '0022_fix_beats_for_reports'),
        ('citrus_borg', '0004_populate_windows_logs'),
    ]

    operations = [
    ]
