# Generated by Django 2.2.6 on 2020-01-17 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    # Note: there is overlap between what 0001_to_0027_initial_model handles
    #       and this. To avoid circular dependencies I have set this as only
    #       replacing the last two migrations. This will cause problems for
    #       anyone who has applied up to a migration less than 00026 (some of
    #       the  fields added here will already exist) unfortunately you will
    #       need to unmigrate citrus borg and run a clean migration.
    replaces = [
        ('citrus_borg', '0026_winlogbeathost_exchange_client_config'),
        ('citrus_borg', '0027_auto_20190819_1308'),
    ]

    dependencies = [
        ('citrus_borg', '0028_0001_to_0027_initial_model'),
        ('mail_collector', '0042_0001_to_0041_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='winlogbeathost',
            name='exchange_client_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail_collector.ExchangeConfiguration', verbose_name='Exchange client configuration'),
        ),
        migrations.AddField(
            model_name='winlogbeathost',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citrus_borg.BorgSite'),
        ),
        migrations.AddField(
            model_name='winlogbeathost',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_winlogbeathost_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='windowslog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_windowslog_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='windowslog',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_windowslog_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='knownbrokeringdevice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_knownbrokeringdevice_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='knownbrokeringdevice',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_knownbrokeringdevice_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='borgsite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_borgsite_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='borgsite',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_borgsite_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='allowedeventsource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_allowedeventsource_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='allowedeventsource',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_allowedeventsource_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.CreateModel(
            name='BorgSiteNotSeen',
            fields=[
            ],
            options={
                'verbose_name': 'Bot Site',
                'verbose_name_plural': 'Bot Sites not seen for a while',
                'ordering': ('-winlogbeathost__last_seen',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('citrus_borg.borgsite',),
        ),
        migrations.CreateModel(
            name='CitrixHost',
            fields=[
            ],
            options={
                'verbose_name': 'Citrix Bot',
                'verbose_name_plural': 'Citrix Bots',
                'ordering': ['-last_seen'],
                'get_latest_by': '-last_seen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('citrus_borg.winlogbeathost',),
        ),
        migrations.CreateModel(
            name='KnownBrokeringDeviceNotSeen',
            fields=[
            ],
            options={
                'verbose_name': 'Citrix App Server',
                'verbose_name_plural': 'Citrix App Servers not seen for a while',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('citrus_borg.knownbrokeringdevice',),
        ),
        migrations.CreateModel(
            name='WinlogbeatHostNotSeen',
            fields=[
            ],
            options={
                'verbose_name': 'Remote Monitoring Bot',
                'verbose_name_plural': 'Remote Monitoring Bots not seen for a while',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('citrus_borg.winlogbeathost',),
        ),
    ]
