# Generated by Django 2.2.6 on 2020-02-27 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import p_soc_auto_base.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citrus_borg', '0029_auto_20200225_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, help_text='object creation time stamp', verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True, help_text='object update time stamp', verbose_name='updated on')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='if this field is checked out, the row will always be excluded from any active operation', verbose_name='enabled')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('uuid', models.UUIDField(db_index=True, default=p_soc_auto_base.utils.get_uuid, unique=True, verbose_name='UUID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_eventcluster_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citrus_borg_eventcluster_updated_by_related', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Cluster of Citrix Logon Failures',
                'verbose_name_plural': 'Clusters of Citrix Logon Failures',
            },
        ),
        migrations.AddField(
            model_name='winlogevent',
            name='cluster',
            field=models.ForeignKey(blank=True, help_text='The cluster this event belongs to. May be null.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citrus_borg.EventCluster', verbose_name='Alert Cluster'),
        ),
    ]
