# Generated by Django 2.2.6 on 2020-07-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citrus_borg', '0032_auto_20200420_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winlogevent',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on'], 'verbose_name': 'Citrix Bot Windows Log Event', 'verbose_name_plural': 'Citrix Bot Windows Log Events'},
        ),
    ]
