# Generated by Django 2.2.6 on 2021-02-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_collector', '0047_auto_20210218_1157'),
        ('citrus_borg', '0034_auto_20201027_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='WinlogbeatHost',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citrus_borg.BorgSite'),
        ),
        migrations.AlterField(
            model_name='WinlogEvent',
            name='source_host',
            field=models.ForeignKey(limit_choices_to={'last_seen__isnull': False}, on_delete=django.db.models.deletion.PROTECT, to='citrus_borg.WinlogbeatHost', verbose_name='Event Source Host'),
        ),
    ]
