# Generated by Django 2.1.1 on 2018-09-24 22:03

from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import User


def populate_levels(apps, schema_editor):
    levels = ['INFO', 'WARNING', 'ERROR', 'CRITICAL', 'ADMINISTRATIVE']
    default_level = 'INFO'
    model = apps.get_model('notifications', 'NotificationLevel')

    user = User.objects.filter(username=settings.NOTIFICATIONS_SERVICE_USER)
    if user.exists():
        user = user.get()
    else:
        user = User.objects.create_user(settings.NOTIFICATIONS_SERVICE_USER)

    for level in levels:
        new_level = model(
            notification_level=level,
            created_by_id=user.id, updated_by_id=user.id)
        if level in default_level:
            new_level.is_default = True

        new_level.save()


def truncate_levels(apps, schema_editor):
    model = apps.get_model('notifications', 'NotificationLevel')

    model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_levels, reverse_code=truncate_levels)
    ]
