# Generated by Django 2.1.1 on 2018-09-25 22:22

from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import User


def populate_broadcast(apps, schema_editor):
    broadcasts = ['email', 'sms', 'log', 'orion_alert']
    default_broadcast = 'email'
    model = apps.get_model('notifications', 'Broadcast')

    user = User.objects.filter(username=settings.NOTIFICATIONS_SERVICE_USER)
    if user.exists():
        user = user.get()
    else:
        user = User.objects.create_user(settings.NOTIFICATIONS_SERVICE_USER)

    for broadcast in broadcasts:
        new_broadcast = model(
            broadcast=broadcast, created_by_id=user.id, updated_by_id=user.id)
        if broadcast in default_broadcast:
            is_default = True

        new_broadcast.save()


def truncate_broadcast(apps, schema_editor):
    model = apps.get_model('notifications', 'Broadcast')

    model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180925_1733'),
    ]

    operations = [
        migrations.RunPython(populate_broadcast,
                             reverse_code=truncate_broadcast)
    ]
