# Generated by Django 2.1.1 on 2018-09-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_populate_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='broadcast_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='broadcast at'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expired_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expired at'),
        ),
    ]
