# Generated by Django 2.1.1 on 2018-09-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20180926_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='essc_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='escalated at'),
        ),
    ]
