# Generated by Django 2.1.1 on 2018-09-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_essc_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='essc_on',
            new_name='esc_on',
        ),
    ]
