# Generated by Django 2.1.1 on 2018-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20180926_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationresponse',
            options={'verbose_name': 'Notification Response', 'verbose_name_plural': 'Notification Responses'},
        ),
        migrations.AddField(
            model_name='notificationresponse',
            name='is_ack_message',
            field=models.BooleanField(db_index=True, default=False, verbose_name='this is the acknowledgement message'),
        ),
    ]
