# Generated by Django 2.1.1 on 2018-09-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20180927_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='expires_automatically',
            field=models.BooleanField(db_index=True, default=False, verbose_name='expires automatically'),
        ),
    ]
