# Generated by Django 2.1 on 2018-08-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertsData',
            fields=[
                ('recid', models.AutoField(primary_key=True, serialize=False)),
                ('valid_start', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_end', models.CharField(blank=True, max_length=100, null=True)),
                ('xmldata', models.TextField(null=True, verbose_name='??')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
