# Generated by Django 2.1 on 2018-08-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocApp', '0002_auto_20180813_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycertsdata',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mycertsdata',
            name='md5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mycertsdata',
            name='sha1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
